In [1]:
import pandas as pd

data = {
    "Department": ["HR", "IT", "IT", "HR", "Finance", "IT", "Finance"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [40000, 60000, 65000, 45000, 70000, 62000, 72000],
    "Experience": [2, 5, 6, 3, 8, 4, 9],
    "City":["Bangalore","Chennai","Kochi","Kochi","Chennai","Kochi","Mumbai"]
}

df = pd.DataFrame(data)
df

  Department Employee  Salary  Experience       City
0         HR        A   40000           2  Bangalore
1         IT        B   60000           5    Chennai
2         IT        C   65000           6      Kochi
3         HR        D   45000           3      Kochi
4    Finance        E   70000           8    Chennai
5         IT        F   62000           4      Kochi
6    Finance        G   72000           9     Mumbai

In [6]:
df.groupby('Department')['Salary'].mean()

Department
Finance    71000.000000
HR         42500.000000
IT         62333.333333
Name: Salary, dtype: float64

In [5]:
df.groupby('Department')['Salary'].sum()

Department
Finance    142000
HR          85000
IT         187000
Name: Salary, dtype: int64

In [7]:
df.groupby('City')['Employee'].count()

City
Bangalore    1
Chennai      2
Kochi        3
Mumbai       1
Name: Employee, dtype: int64

In [9]:
df.groupby('Department')['Experience'].agg(['max','min'])

            max  min
Department
Finance       9    8
HR            3    2
IT            6    4

In [13]:
df.groupby(["Department"]).agg({
    "Salary": ["mean", "max"],
    "Experience": ["min", "max"]
})

                  Salary        Experience
                    mean    max        min max
Department
Finance     71000.000000  72000          8   9
HR          42500.000000  45000          2   3
IT          62333.333333  65000          4   6

In [16]:
df.groupby('Department').agg(
    Average_Salary = ('Salary','mean'),
    Maximum_Salary = ('Salary','max'),
    Minumun_Experience = ('Experience','min'),
    Maximum_Experience = ('Experience','max')
)

,Average_Salary,Maximum_Salary,Minumun_Experience,Maximum_Experience
Department,,,,
Finance,71000.000000,72000,8,9
HR,42500.000000,45000,2,3
IT,62333.333333,65000,4,6

In [ ]:
df.groupby(['Department,'Experience'])['Salary'