In [185]:
import numpy as np
import pandas as pd

In [186]:
df = pd.read_csv('Titanic-Dataset.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [187]:
# 1
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [188]:
# 2
df.head(11)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S

In [189]:
# 3
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [190]:
# 4
df.tail(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [191]:
# 5
df.shape

(891, 12)

In [192]:
# 6
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='str')

In [193]:
# 7
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [194]:
# 8
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 118.9 KB

In [195]:
# 9
df.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]>

In [196]:
# 10
df.size

10692

In [197]:
# 11
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [198]:
# 12
df.isnull().sum().sum()

np.int64(866)

In [199]:
# 13
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [200]:
# 14
df_age_filled = df.copy()
age_mean = df_age_filled['Age'].mean()
df_age_filled['Age'] = df_age_filled['Age'].fillna(age_mean)
df_age_filled['Age']

0      22.000000
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
886    27.000000
887    19.000000
888    29.699118
889    26.000000
890    32.000000
Name: Age, Length: 891, dtype: float64

In [201]:
# 15
df_embarked_filled =df
embarked_mode = df['Embarked'].mode()[0]
df_embarked_filled = df['Embarked'].fillna(embarked_mode)
df_embarked_filled

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: str

In [202]:
df[df['Embarked'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
61,62,1,1,"Icard, Miss. Amelie",female,38.0,0,0,113572,80.0,B28,NaN
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0,B28,NaN

In [203]:
# 16
print(df.shape)
df_no_missing_values = df.dropna()
print(df_no_missing_values.shape)

(891, 12)
(183, 12)

In [204]:
# 17
df_no_missing_columns = df.dropna(axis=1)
df_no_missing_columns

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500

In [205]:
# 18
df.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [206]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [207]:
# 20
print(df["Fare"])

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [208]:
# 21
print(df[["Name", "Age"]])

                                                  Name   Age
0                              Braund, Mr. Owen Harris  22.0
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2                               Heikkinen, Miss. Laina  26.0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4                             Allen, Mr. William Henry  35.0
..                                                 ...   ...
886                              Montvila, Rev. Juozas  27.0
887                       Graham, Miss. Margaret Edith  19.0
888           Johnston, Miss. Catherine Helen "Carrie"   NaN
889                              Behr, Mr. Karl Howell  26.0
890                                Dooley, Mr. Patrick  32.0

[891 rows x 2 columns]

In [209]:
# 22
print(df[["Name", "Sex", "Age", "Fare"]])

                                                  Name     Sex   Age     Fare
0                              Braund, Mr. Owen Harris    male  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0  71.2833
2                               Heikkinen, Miss. Laina  female  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0  53.1000
4                             Allen, Mr. William Henry    male  35.0   8.0500
..                                                 ...     ...   ...      ...
886                              Montvila, Rev. Juozas    male  27.0  13.0000
887                       Graham, Miss. Margaret Edith  female  19.0  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN  23.4500
889                              Behr, Mr. Karl Howell    male  26.0  30.0000
890                                Dooley, Mr. Patrick    male  32.0   7.7500

[891 rows x 4 columns]

In [210]:
# 23
print(df.select_dtypes(include="number"))

     PassengerId  Survived  Pclass   Age  SibSp  Parch     Fare
0              1         0       3  22.0      1      0   7.2500
1              2         1       1  38.0      1      0  71.2833
2              3         1       3  26.0      0      0   7.9250
3              4         1       1  35.0      1      0  53.1000
4              5         0       3  35.0      0      0   8.0500
..           ...       ...     ...   ...    ...    ...      ...
886          887         0       2  27.0      0      0  13.0000
887          888         1       1  19.0      0      0  30.0000
888          889         0       3   NaN      1      2  23.4500
889          890         1       1  26.0      0      0  30.0000
890          891         0       3  32.0      0      0   7.7500

[891 rows x 7 columns]

In [211]:
# 24
print(df.loc[df['Age'] > 30])

     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
4              5         0       3
6              7         0       1
11            12         1       1
..           ...       ...     ...
873          874         0       3
879          880         1       1
881          882         0       3
885          886         0       3
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
6                              McCarthy, Mr. Timothy J    male  54.0      0
11                            Bonnell, Miss. Elizabeth  female  58.0      0
..                                                 ...     ...   ...    ...
873                        Vander Cruyssen, Mr. Victor    male  47.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
881                                 Markun, Mr. Johann    male  33.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch    Ticket     Fare Cabin Embarked
1        0  PC 17599  71.2833   C85        C
3        0    113803  53.1000  C123        S
4        0    373450   8.0500   NaN        S
6        0     17463  51.8625   E46        S
11       0    113783  26.5500  C103        S
..     ...       ...      ...   ...      ...
873      0    345765   9.0000   NaN        S
879      1     11767  83.1583   C50        C
881      0    349257   7.8958   NaN        S
885      5    382652  29.1250   NaN        Q
890      0    370376   7.7500   NaN        Q

[305 rows x 12 columns]

In [212]:
# 25
print(df.loc[df["Age"] < 18])

     PassengerId  Survived  Pclass                                     Name  \
7              8         0       3           Palsson, Master. Gosta Leonard
9             10         1       2      Nasser, Mrs. Nicholas (Adele Achem)
10            11         1       3          Sandstrom, Miss. Marguerite Rut
14            15         0       3     Vestrom, Miss. Hulda Amanda Adolfina
16            17         0       3                     Rice, Master. Eugene
..           ...       ...     ...                                      ...
850          851         0       3  Andersson, Master. Sigvard Harald Elias
852          853         0       3                  Boulos, Miss. Nourelain
853          854         1       1                Lines, Miss. Mary Conover
869          870         1       3          Johnson, Master. Harold Theodor
875          876         1       3         Najib, Miss. Adele Kiamie "Jane"

        Sex   Age  SibSp  Parch    Ticket     Fare Cabin Embarked
7      male   2.0      3      1    349909  21.0750   NaN        S
9    female  14.0      1      0    237736  30.0708   NaN        C
10   female   4.0      1      1   PP 9549  16.7000    G6        S
14   female  14.0      0      0    350406   7.8542   NaN        S
16     male   2.0      4      1    382652  29.1250   NaN        Q
..      ...   ...    ...    ...       ...      ...   ...      ...
850    male   4.0      4      2    347082  31.2750   NaN        S
852  female   9.0      1      1      2678  15.2458   NaN        C
853  female  16.0      0      1  PC 17592  39.4000   D28        S
869    male   4.0      1      1    347742  11.1333   NaN        S
875  female  15.0      0      0      2667   7.2250   NaN        C

[113 rows x 12 columns]

In [213]:
# 26
print(df.loc[df['Sex'] == 'female'])

     PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
880          881         1       2
882          883         0       3
885          886         0       3
887          888         1       1
888          889         0       3

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
..                                                 ...     ...   ...    ...
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1

     Parch            Ticket     Fare Cabin Embarked
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
8        2            347742  11.1333   NaN        S
9        0            237736  30.0708   NaN        C
..     ...               ...      ...   ...      ...
880      1            230433  26.0000   NaN        S
882      0              7552  10.5167   NaN        S
885      5            382652  29.1250   NaN        Q
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S

[314 rows x 12 columns]

In [214]:
# 27
print(df.loc[df["Sex"] == "male"])

     PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male
4              5         0       3        Allen, Mr. William Henry  male
5              6         0       3                Moran, Mr. James  male
6              7         0       1         McCarthy, Mr. Timothy J  male
7              8         0       3  Palsson, Master. Gosta Leonard  male
..           ...       ...     ...                             ...   ...
883          884         0       2   Banfield, Mr. Frederick James  male
884          885         0       3          Sutehall, Mr. Henry Jr  male
886          887         0       2           Montvila, Rev. Juozas  male
889          890         1       1           Behr, Mr. Karl Howell  male
890          891         0       3             Dooley, Mr. Patrick  male

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0    22.0      1      0         A/5 21171   7.2500   NaN        S
4    35.0      0      0            373450   8.0500   NaN        S
5     NaN      0      0            330877   8.4583   NaN        Q
6    54.0      0      0             17463  51.8625   E46        S
7     2.0      3      1            349909  21.0750   NaN        S
..    ...    ...    ...               ...      ...   ...      ...
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
886  27.0      0      0            211536  13.0000   NaN        S
889  26.0      0      0            111369  30.0000  C148        C
890  32.0      0      0            370376   7.7500   NaN        Q

[577 rows x 12 columns]

In [215]:
# 28
print(df.loc[df["Survived"] == 1])

     PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
875          876         1       3
879          880         1       1
880          881         1       2
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
..                                                 ...     ...   ...    ...
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch            Ticket     Fare Cabin Embarked
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
8        2            347742  11.1333   NaN        S
9        0            237736  30.0708   NaN        C
..     ...               ...      ...   ...      ...
875      0              2667   7.2250   NaN        C
879      1             11767  83.1583   C50        C
880      1            230433  26.0000   NaN        S
887      0            112053  30.0000   B42        S
889      0            111369  30.0000  C148        C

[342 rows x 12 columns]

In [216]:
# 29
print(df.loc[df["Survived"] == 0])

     PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris
4              5         0       3                  Allen, Mr. William Henry
5              6         0       3                          Moran, Mr. James
6              7         0       1                   McCarthy, Mr. Timothy J
7              8         0       3            Palsson, Master. Gosta Leonard
..           ...       ...     ...                                       ...
884          885         0       3                    Sutehall, Mr. Henry Jr
885          886         0       3      Rice, Mrs. William (Margaret Norton)
886          887         0       2                     Montvila, Rev. Juozas
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch           Ticket     Fare Cabin Embarked
0      male  22.0      1      0        A/5 21171   7.2500   NaN        S
4      male  35.0      0      0           373450   8.0500   NaN        S
5      male   NaN      0      0           330877   8.4583   NaN        Q
6      male  54.0      0      0            17463  51.8625   E46        S
7      male   2.0      3      1           349909  21.0750   NaN        S
..      ...   ...    ...    ...              ...      ...   ...      ...
884    male  25.0      0      0  SOTON/OQ 392076   7.0500   NaN        S
885  female  39.0      0      5           382652  29.1250   NaN        Q
886    male  27.0      0      0           211536  13.0000   NaN        S
888  female   NaN      1      2       W./C. 6607  23.4500   NaN        S
890    male  32.0      0      0           370376   7.7500   NaN        Q

[549 rows x 12 columns]

In [217]:
# 30
print(df.loc[(df['Sex']=='female') & (df['Survived'] == 1)])

     PassengerId  Survived  Pclass  \
1              2         1       1
2              3         1       3
3              4         1       1
8              9         1       3
9             10         1       2
..           ...       ...     ...
874          875         1       2
875          876         1       3
879          880         1       1
880          881         1       2
887          888         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
..                                                 ...     ...   ...    ...
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1
875                   Najib, Miss. Adele Kiamie "Jane"  female  15.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0

     Parch            Ticket     Fare Cabin Embarked
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
8        2            347742  11.1333   NaN        S
9        0            237736  30.0708   NaN        C
..     ...               ...      ...   ...      ...
874      0         P/PP 3381  24.0000   NaN        C
875      0              2667   7.2250   NaN        C
879      1             11767  83.1583   C50        C
880      1            230433  26.0000   NaN        S
887      0            112053  30.0000   B42        S

[233 rows x 12 columns]

In [218]:
# 31
print(df.loc[df["Fare"] > 100])

     PassengerId  Survived  Pclass  \
27            28         0       1
31            32         1       1
88            89         1       1
118          119         0       1
195          196         1       1
215          216         1       1
258          259         1       1
268          269         1       1
269          270         1       1
297          298         0       1
299          300         1       1
305          306         1       1
306          307         1       1
307          308         1       1
311          312         1       1
318          319         1       1
319          320         1       1
325          326         1       1
332          333         0       1
334          335         1       1
337          338         1       1
341          342         1       1
373          374         0       1
377          378         0       1
380          381         1       1
390          391         1       1
393          394         1       1
435          436         1       1
438          439         0       1
498          499         0       1
505          506         0       1
527          528         0       1
537          538         1       1
544          545         0       1
550          551         1       1
557          558         0       1
581          582         1       1
609          610         1       1
659          660         0       1
660          661         1       1
679          680         1       1
689          690         1       1
698          699         0       1
700          701         1       1
708          709         1       1
716          717         1       1
730          731         1       1
737          738         1       1
742          743         1       1
763          764         1       1
779          780         1       1
802          803         1       1
856          857         1       1

                                                  Name     Sex    Age  SibSp  \
27                      Fortune, Mr. Charles Alexander    male  19.00      3
31      Spencer, Mrs. William Augustus (Marie Eugenie)  female    NaN      1
88                          Fortune, Miss. Mabel Helen  female  23.00      3
118                           Baxter, Mr. Quigg Edmond    male  24.00      0
195                               Lurette, Miss. Elise  female  58.00      0
215                            Newell, Miss. Madeleine  female  31.00      1
258                                   Ward, Miss. Anna  female  35.00      0
268      Graham, Mrs. William Thompson (Edith Junkins)  female  58.00      0
269                             Bissette, Miss. Amelia  female  35.00      0
297                       Allison, Miss. Helen Loraine  female   2.00      1
299    Baxter, Mrs. James (Helene DeLaudeniere Chaput)  female  50.00      0
305                     Allison, Master. Hudson Trevor    male   0.92      1
306                            Fleming, Miss. Margaret  female    NaN      0
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.00      1
311                         Ryerson, Miss. Emily Borie  female  18.00      2
318                           Wick, Miss. Mary Natalie  female  31.00      0
319  Spedden, Mrs. Frederic Oakley (Margaretta Corn...  female  40.00      1
325                           Young, Miss. Marie Grice  female  36.00      0
332                          Graham, Mr. George Edward    male  38.00      0
334  Frauenthal, Mrs. Henry William (Clara Heinshei...  female    NaN      1
337                    Burns, Miss. Elizabeth Margaret  female  41.00      0
341                     Fortune, Miss. Alice Elizabeth  female  24.00      3
373                                Ringhini, Mr. Sante    male  22.00      0
377                          Widener, Mr. Harry Elkins    male  27.00      0
380                              Bidois, Miss. Rosalie  female  42.00      0
390                         Carter, Mr. William Ernest    male  36.00      1
393                             Newell, Miss. Marjorie  female  23.00      1
435                          Carter, Miss. Lucile Polk  female  14.00      1
438                                  Fortune, Mr. Mark    male  64.00      1
498    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00      1
505         Penasco y Castellana, Mr. Victor de Satode    male  18.00      1
527                                 Farthing, Mr. John    male    NaN      0
537                                LeRoy, Miss. Bertha  female  30.00      0
544                         Douglas, Mr. Walter Donald    male  50.00      1
550                        Thayer, Mr. John Borland Jr    male  17.00      0
557                                Robbins, Mr. Victor    male    NaN      0
581  Thayer, Mrs. John Borland (Marian Longstreth M...  female  39.00      1
609                          Shutes, Miss. Elizabeth W  female  40.00      0
659                         Newell, Mr. Arthur Webster    male  58.00      0
660                      Frauenthal, Dr. Henry William    male  50.00      2
679                 Cardeza, Mr. Thomas Drake Martinez    male  36.00      0
689                  Madill, Miss. Georgette Alexandra  female  15.00      0
698                           Thayer, Mr. John Borland    male  49.00      1
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  female  18.00      1
708                               Cleaver, Miss. Alice  female  22.00      0
716                      Endres, Miss. Caroline Louise  female  38.00      0
730                      Allen, Miss. Elisabeth Walton  female  29.00      0
737                             Lesurer, Mr. Gustave J    male  35.00      0
742              Ryerson, Miss. Susan Parker "Suzette"  female  21.00      2
763          Carter, Mrs. William Ernest (Lucile Polk)  female  36.00      1
779  Robert, Mrs. Edward Scott (Elisabeth Walton Mc...  female  43.00      0
802                Carter, Master. William Thornton II    male  11.00      1
856         Wick, Mrs. George Dennick (Mary Hitchcock)  female  45.00      1

     Parch    Ticket      Fare            Cabin Embarked
27       2     19950  263.0000      C23 C25 C27        S
31       0  PC 17569  146.5208              B78        C
88       2     19950  263.0000      C23 C25 C27        S
118      1  PC 17558  247.5208          B58 B60        C
195      0  PC 17569  146.5208              B80        C
215      0     35273  113.2750              D36        C
258      0  PC 17755  512.3292              NaN        C
268      1  PC 17582  153.4625             C125        S
269      0  PC 17760  135.6333              C99        S
297      2    113781  151.5500          C22 C26        S
299      1  PC 17558  247.5208          B58 B60        C
305      2    113781  151.5500          C22 C26        S
306      0     17421  110.8833              NaN        C
307      0  PC 17758  108.9000              C65        C
311      2  PC 17608  262.3750  B57 B59 B63 B66        C
318      2     36928  164.8667               C7        S
319      1     16966  134.5000              E34        C
325      0  PC 17760  135.6333              C32        C
332      1  PC 17582  153.4625              C91        S
334      0  PC 17611  133.6500              NaN        S
337      0     16966  134.5000              E40        C
341      2     19950  263.0000      C23 C25 C27        S
373      0  PC 17760  135.6333              NaN        C
377      2    113503  211.5000              C82        C
380      0  PC 17757  227.5250              NaN        C
390      2    113760  120.0000          B96 B98        S
393      0     35273  113.2750              D36        C
435      2    113760  120.0000          B96 B98        S
438      4     19950  263.0000      C23 C25 C27        S
498      2    113781  151.5500          C22 C26        S
505      0  PC 17758  108.9000              C65        C
527      0  PC 17483  221.7792              C95        S
537      0  PC 17761  106.4250              NaN        C
544      0  PC 17761  106.4250              C86        C
550      2     17421  110.8833              C70        C
557      0  PC 17757  227.5250              NaN        C
581      1     17421  110.8833              C68        C
609      0  PC 17582  153.4625             C125        S
659      2     35273  113.2750              D48        C
660      0  PC 17611  133.6500              NaN        S
679      1  PC 17755  512.3292      B51 B53 B55        C
689      1     24160  211.3375               B5        S
698      1     17421  110.8833              C68        C
700      0  PC 17757  227.5250          C62 C64        C
708      0    113781  151.5500              NaN        S
716      0  PC 17757  227.5250              C45        C
730      0     24160  211.3375               B5        S
737      0  PC 17755  512.3292             B101        C
742      2  PC 17608  262.3750  B57 B59 B63 B66        C
763      2    113760  120.0000          B96 B98        S
779      1     24160  211.3375               B3        S
802      2    113760  120.0000          B96 B98        S
856      1     36928  164.8667              NaN        S

In [219]:
# 32
print(df.loc[df["Pclass"] == 1])

     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
6              7         0       1
11            12         1       1
23            24         1       1
..           ...       ...     ...
871          872         1       1
872          873         0       1
879          880         1       1
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
6                              McCarthy, Mr. Timothy J    male  54.0      0
11                            Bonnell, Miss. Elizabeth  female  58.0      0
23                        Sloper, Mr. William Thompson    male  28.0      0
..                                                 ...     ...   ...    ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
872                           Carlsson, Mr. Frans Olof    male  33.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch    Ticket     Fare        Cabin Embarked
1        0  PC 17599  71.2833          C85        C
3        0    113803  53.1000         C123        S
6        0     17463  51.8625          E46        S
11       0    113783  26.5500         C103        S
23       0    113788  35.5000           A6        S
..     ...       ...      ...          ...      ...
871      1     11751  52.5542          D35        S
872      0       695   5.0000  B51 B53 B55        S
879      1     11767  83.1583          C50        C
887      0    112053  30.0000          B42        S
889      0    111369  30.0000         C148        C

[216 rows x 12 columns]

In [220]:
# 33
print(df.loc[df["Pclass"] == 3])

     PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris
2              3         1       3                    Heikkinen, Miss. Laina
4              5         0       3                  Allen, Mr. William Henry
5              6         0       3                          Moran, Mr. James
7              8         0       3            Palsson, Master. Gosta Leonard
..           ...       ...     ...                                       ...
882          883         0       3              Dahlberg, Miss. Gerda Ulrika
884          885         0       3                    Sutehall, Mr. Henry Jr
885          886         0       3      Rice, Mrs. William (Margaret Norton)
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
4      male  35.0      0      0            373450   8.0500   NaN        S
5      male   NaN      0      0            330877   8.4583   NaN        Q
7      male   2.0      3      1            349909  21.0750   NaN        S
..      ...   ...    ...    ...               ...      ...   ...      ...
882  female  22.0      0      0              7552  10.5167   NaN        S
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S
885  female  39.0      0      5            382652  29.1250   NaN        Q
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S
890    male  32.0      0      0            370376   7.7500   NaN        Q

[491 rows x 12 columns]

In [221]:
# 34
print(df.loc[(df["Sex"] == "male") & (df["Survived"] == 1)])

     PassengerId  Survived  Pclass                             Name   Sex  \
17            18         1       2     Williams, Mr. Charles Eugene  male
21            22         1       2            Beesley, Mr. Lawrence  male
23            24         1       1     Sloper, Mr. William Thompson  male
36            37         1       3                 Mamee, Mr. Hanna  male
55            56         1       1                Woolner, Mr. Hugh  male
..           ...       ...     ...                              ...   ...
838          839         1       3                  Chip, Mr. Chang  male
839          840         1       1             Marechal, Mr. Pierre  male
857          858         1       1           Daly, Mr. Peter Denis   male
869          870         1       3  Johnson, Master. Harold Theodor  male
889          890         1       1            Behr, Mr. Karl Howell  male

      Age  SibSp  Parch  Ticket     Fare Cabin Embarked
17    NaN      0      0  244373  13.0000   NaN        S
21   34.0      0      0  248698  13.0000   D56        S
23   28.0      0      0  113788  35.5000    A6        S
36    NaN      0      0    2677   7.2292   NaN        C
55    NaN      0      0   19947  35.5000   C52        S
..    ...    ...    ...     ...      ...   ...      ...
838  32.0      0      0    1601  56.4958   NaN        S
839   NaN      0      0   11774  29.7000   C47        C
857  51.0      0      0  113055  26.5500   E17        S
869   4.0      1      1  347742  11.1333   NaN        S
889  26.0      0      0  111369  30.0000  C148        C

[109 rows x 12 columns]

In [222]:
# 35
print(df.loc[(df["Sex"] == "female") & (df["Survived"] == 0)])

     PassengerId  Survived  Pclass  \
14            15         0       3
18            19         0       3
24            25         0       3
38            39         0       3
40            41         0       3
..           ...       ...     ...
854          855         0       2
863          864         0       3
882          883         0       3
885          886         0       3
888          889         0       3

                                                  Name     Sex   Age  SibSp  \
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1
24                       Palsson, Miss. Torborg Danira  female   8.0      3
38                  Vander Planke, Miss. Augusta Maria  female  18.0      2
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.0      1
..                                                 ...     ...   ...    ...
854      Carter, Mrs. Ernest Courtenay (Lilian Hughes)  female  44.0      1
863                  Sage, Miss. Dorothy Edith "Dolly"  female   NaN      8
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1

     Parch      Ticket     Fare Cabin Embarked
14       0      350406   7.8542   NaN        S
18       0      345763  18.0000   NaN        S
24       1      349909  21.0750   NaN        S
38       0      345764  18.0000   NaN        S
40       0        7546   9.4750   NaN        S
..     ...         ...      ...   ...      ...
854      0      244252  26.0000   NaN        S
863      2    CA. 2343  69.5500   NaN        S
882      0        7552  10.5167   NaN        S
885      5      382652  29.1250   NaN        Q
888      2  W./C. 6607  23.4500   NaN        S

[81 rows x 12 columns]

In [223]:
# 36
print(df.sort_values("Age"))

     PassengerId  Survived  Pclass                                      Name  \
803          804         1       3           Thomas, Master. Assad Alexander
755          756         1       2                 Hamalainen, Master. Viljo
644          645         1       3                    Baclini, Miss. Eugenie
469          470         1       3             Baclini, Miss. Helene Barbara
78            79         1       2             Caldwell, Master. Alden Gates
..           ...       ...     ...                                       ...
859          860         0       3                          Razi, Mr. Raihed
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"
868          869         0       3               van Melkebeke, Mr. Philemon
878          879         0       3                        Laleff, Mr. Kristo
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked
803    male  0.42      0      1        2625   8.5167   NaN        C
755    male  0.67      1      1      250649  14.5000   NaN        S
644  female  0.75      2      1        2666  19.2583   NaN        C
469  female  0.75      2      1        2666  19.2583   NaN        C
78     male  0.83      0      2      248738  29.0000   NaN        S
..      ...   ...    ...    ...         ...      ...   ...      ...
859    male   NaN      0      0        2629   7.2292   NaN        C
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S
868    male   NaN      0      0      345777   9.5000   NaN        S
878    male   NaN      0      0      349217   7.8958   NaN        S
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S

[891 rows x 12 columns]

In [224]:
# 37
print(df.sort_values("Age", ascending=False))

     PassengerId  Survived  Pclass                                      Name  \
630          631         1       1      Barkworth, Mr. Algernon Henry Wilson
851          852         0       3                       Svensson, Mr. Johan
493          494         0       1                   Artagaveytia, Mr. Ramon
96            97         0       1                 Goldschmidt, Mr. George B
116          117         0       3                      Connors, Mr. Patrick
..           ...       ...     ...                                       ...
859          860         0       3                          Razi, Mr. Raihed
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"
868          869         0       3               van Melkebeke, Mr. Philemon
878          879         0       3                        Laleff, Mr. Kristo
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"

        Sex   Age  SibSp  Parch      Ticket     Fare Cabin Embarked
630    male  80.0      0      0       27042  30.0000   A23        S
851    male  74.0      0      0      347060   7.7750   NaN        S
493    male  71.0      0      0    PC 17609  49.5042   NaN        C
96     male  71.0      0      0    PC 17754  34.6542    A5        C
116    male  70.5      0      0      370369   7.7500   NaN        Q
..      ...   ...    ...    ...         ...      ...   ...      ...
859    male   NaN      0      0        2629   7.2292   NaN        C
863  female   NaN      8      2    CA. 2343  69.5500   NaN        S
868    male   NaN      0      0      345777   9.5000   NaN        S
878    male   NaN      0      0      349217   7.8958   NaN        S
888  female   NaN      1      2  W./C. 6607  23.4500   NaN        S

[891 rows x 12 columns]

In [225]:
# 38
print(df.sort_values("Fare"))

     PassengerId  Survived  Pclass                                Name  \
815          816         0       1                    Fry, Mr. Richard
806          807         0       1              Andrews, Mr. Thomas Jr
413          414         0       2      Cunningham, Mr. Alfred Fleming
481          482         0       2    Frost, Mr. Anthony Wood "Archie"
302          303         0       3     Johnson, Mr. William Cahoone Jr
..           ...       ...     ...                                 ...
438          439         0       1                   Fortune, Mr. Mark
341          342         1       1      Fortune, Miss. Alice Elizabeth
737          738         1       1              Lesurer, Mr. Gustave J
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez
258          259         1       1                    Ward, Miss. Anna

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked
815    male   NaN      0      0    112058    0.0000         B102        S
806    male  39.0      0      0    112050    0.0000          A36        S
413    male   NaN      0      0    239853    0.0000          NaN        S
481    male   NaN      0      0    239854    0.0000          NaN        S
302    male  19.0      0      0      LINE    0.0000          NaN        S
..      ...   ...    ...    ...       ...       ...          ...      ...
438    male  64.0      1      4     19950  263.0000  C23 C25 C27        S
341  female  24.0      3      2     19950  263.0000  C23 C25 C27        S
737    male  35.0      0      0  PC 17755  512.3292         B101        C
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C
258  female  35.0      0      0  PC 17755  512.3292          NaN        C

[891 rows x 12 columns]

In [226]:
# 39
print(df.sort_values("Fare", ascending=False))

     PassengerId  Survived  Pclass                                Name  \
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez
258          259         1       1                    Ward, Miss. Anna
737          738         1       1              Lesurer, Mr. Gustave J
88            89         1       1          Fortune, Miss. Mabel Helen
438          439         0       1                   Fortune, Mr. Mark
..           ...       ...     ...                                 ...
806          807         0       1              Andrews, Mr. Thomas Jr
815          816         0       1                    Fry, Mr. Richard
466          467         0       2               Campbell, Mr. William
481          482         0       2    Frost, Mr. Anthony Wood "Archie"
822          823         0       1     Reuchlin, Jonkheer. John George

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C
258  female  35.0      0      0  PC 17755  512.3292          NaN        C
737    male  35.0      0      0  PC 17755  512.3292         B101        C
88   female  23.0      3      2     19950  263.0000  C23 C25 C27        S
438    male  64.0      1      4     19950  263.0000  C23 C25 C27        S
..      ...   ...    ...    ...       ...       ...          ...      ...
806    male  39.0      0      0    112050    0.0000          A36        S
815    male   NaN      0      0    112058    0.0000         B102        S
466    male   NaN      0      0    239853    0.0000          NaN        S
481    male   NaN      0      0    239854    0.0000          NaN        S
822    male  38.0      0      0     19972    0.0000          NaN        S

[891 rows x 12 columns]

In [227]:
# 40
print(df.sort_values(["Pclass", "Age"]))

     PassengerId  Survived  Pclass                                      Name  \
305          306         1       1            Allison, Master. Hudson Trevor
297          298         0       1              Allison, Miss. Helen Loraine
445          446         1       1                 Dodge, Master. Washington
802          803         1       1       Carter, Master. William Thornton II
435          436         1       1                 Carter, Miss. Lucile Polk
..           ...       ...     ...                                       ...
859          860         0       3                          Razi, Mr. Raihed
863          864         0       3         Sage, Miss. Dorothy Edith "Dolly"
868          869         0       3               van Melkebeke, Mr. Philemon
878          879         0       3                        Laleff, Mr. Kristo
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"

        Sex    Age  SibSp  Parch      Ticket      Fare    Cabin Embarked
305    male   0.92      1      2      113781  151.5500  C22 C26        S
297  female   2.00      1      2      113781  151.5500  C22 C26        S
445    male   4.00      0      2       33638   81.8583      A34        S
802    male  11.00      1      2      113760  120.0000  B96 B98        S
435  female  14.00      1      2      113760  120.0000  B96 B98        S
..      ...    ...    ...    ...         ...       ...      ...      ...
859    male    NaN      0      0        2629    7.2292      NaN        C
863  female    NaN      8      2    CA. 2343   69.5500      NaN        S
868    male    NaN      0      0      345777    9.5000      NaN        S
878    male    NaN      0      0      349217    7.8958      NaN        S
888  female    NaN      1      2  W./C. 6607   23.4500      NaN        S

[891 rows x 12 columns]

In [228]:
# 41
print(df.sort_values(["Fare", "Age"], ascending=False))

     PassengerId  Survived  Pclass                                Name  \
679          680         1       1  Cardeza, Mr. Thomas Drake Martinez
258          259         1       1                    Ward, Miss. Anna
737          738         1       1              Lesurer, Mr. Gustave J
438          439         0       1                   Fortune, Mr. Mark
341          342         1       1      Fortune, Miss. Alice Elizabeth
..           ...       ...     ...                                 ...
481          482         0       2    Frost, Mr. Anthony Wood "Archie"
633          634         0       1       Parr, Mr. William Henry Marsh
674          675         0       2          Watson, Mr. Ennis Hastings
732          733         0       2                Knight, Mr. Robert J
815          816         0       1                    Fry, Mr. Richard

        Sex   Age  SibSp  Parch    Ticket      Fare        Cabin Embarked
679    male  36.0      0      1  PC 17755  512.3292  B51 B53 B55        C
258  female  35.0      0      0  PC 17755  512.3292          NaN        C
737    male  35.0      0      0  PC 17755  512.3292         B101        C
438    male  64.0      1      4     19950  263.0000  C23 C25 C27        S
341  female  24.0      3      2     19950  263.0000  C23 C25 C27        S
..      ...   ...    ...    ...       ...       ...          ...      ...
481    male   NaN      0      0    239854    0.0000          NaN        S
633    male   NaN      0      0    112052    0.0000          NaN        S
674    male   NaN      0      0    239856    0.0000          NaN        S
732    male   NaN      0      0    239855    0.0000          NaN        S
815    male   NaN      0      0    112058    0.0000         B102        S

[891 rows x 12 columns]

In [229]:
# 42
print(df["Pclass"].unique())
print(df.isnull().sum())

[3 1 2]
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [230]:
# 43
print(df["Pclass"].nunique())

3

In [231]:
# 44
print(df["Embarked"].unique())

<ArrowStringArray>
['S', 'C', 'Q', nan]
Length: 4, dtype: str

In [232]:
# 45
print(df["Embarked"].nunique())

3

In [233]:
# 46
print(df["Sex"].unique())

<ArrowStringArray>
['male', 'female']
Length: 2, dtype: str

In [234]:
# 47
print(df["Sex"].value_counts())

Sex
male      577
female    314
Name: count, dtype: int64

In [235]:
# 48
print(df["Pclass"].value_counts())

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [236]:
# 49
print(df["Embarked"].value_counts())

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [237]:
# 50
print(df["Sex"].value_counts(normalize=True) * 100)

Sex
male      64.758698
female    35.241302
Name: proportion, dtype: float64

In [238]:
# 51
print(df["Pclass"].value_counts(normalize=True) * 100)

Pclass
3    55.106622
1    24.242424
2    20.650954
Name: proportion, dtype: float64

In [239]:
# 52
print(df["Age"].mean())

29.69911764705882

In [240]:
# 53
print(df["Fare"].mean())

32.204207968574636

In [241]:
# 54
print(df["Age"].max())

80.0

In [242]:
# 55
print(df["Age"].min())

0.42

In [243]:
# 56
print(df["Fare"].max())

512.3292

In [244]:
# 57
print(df["Fare"].min())

0.0

In [245]:
# 58
print(df["Age"].median())

28.0

In [246]:
# 59
print(df["Fare"].median())

14.4542

In [247]:
# 60
print(df["Age"].std())

14.526497332334042

In [248]:
# 61
print(df["Fare"].var())

2469.436845743116

In [249]:
# 62
print(df["Fare"].sum())

28693.9493

In [250]:
# 63
print(df.groupby("Sex")["Age"].mean())

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [251]:
# 64
print(df.groupby("Sex")["Fare"].mean())

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

In [252]:
# 65
print(df.groupby("Pclass")["Fare"].mean())

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [253]:
# 66
print(df.groupby("Pclass")["PassengerId"].count())

Pclass
1    216
2    184
3    491
Name: PassengerId, dtype: int64

In [254]:
# 67
print(df.groupby("Sex")["Age"].max())

Sex
female    63.0
male      80.0
Name: Age, dtype: float64

In [255]:
# 68
print(df.groupby("Pclass")["Fare"].min())

Pclass
1    0.0
2    0.0
3    0.0
Name: Fare, dtype: float64

In [256]:
# 69
print(df.groupby("Pclass")["Fare"].sum())

Pclass
1    18177.4125
2     3801.8417
3     6714.6951
Name: Fare, dtype: float64

In [257]:
# 70
print(df.groupby("Pclass")["Survived"].sum())

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [258]:
# 71
print(df.groupby("Pclass")["Age"].agg(["mean", "max", "min"]))

             mean   max   min
Pclass
1       38.233441  80.0  0.92
2       29.877630  70.0  0.67
3       25.140620  74.0  0.42

In [259]:
# 72
print(df.groupby("Sex")["Fare"].agg(["mean", "max", "min"]))

             mean       max   min
Sex
female  44.479818  512.3292  6.75
male    25.523893  512.3292  0.00

In [260]:
# 73
print(df.groupby("Pclass").agg(mean_fare=("Fare", "mean"),total_fare=("Fare", "sum"),passenger_count=("PassengerId", "count")))

        mean_fare  total_fare  passenger_count
Pclass
1       84.154687  18177.4125              216
2       20.662183   3801.8417              184
3       13.675550   6714.6951              491

In [261]:
# 74
print(df.groupby("Sex").agg({"Age": "mean", "Fare": "mean"}))

              Age       Fare
Sex
female  27.915709  44.479818
male    30.726645  25.523893

In [262]:
# 75
print(df.iloc[:20])

    PassengerId  Survived  Pclass  \
0             1         0       3
1             2         1       1
2             3         1       3
3             4         1       1
4             5         0       3
5             6         0       3
6             7         0       1
7             8         0       3
8             9         1       3
9            10         1       2
10           11         1       3
11           12         1       1
12           13         0       3
13           14         0       3
14           15         0       3
15           16         1       2
16           17         0       3
17           18         1       2
18           19         0       3
19           20         1       3

                                                 Name     Sex   Age  SibSp  \
0                             Braund, Mr. Owen Harris    male  22.0      1
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                              Heikkinen, Miss. Laina  female  26.0      0
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
5                                    Moran, Mr. James    male   NaN      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
7                      Palsson, Master. Gosta Leonard    male   2.0      3
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                 Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1
11                           Bonnell, Miss. Elizabeth  female  58.0      0
12                     Saundercock, Mr. William Henry    male  20.0      0
13                        Andersson, Mr. Anders Johan    male  39.0      1
14               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0
15                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0
16                               Rice, Master. Eugene    male   2.0      4
17                       Williams, Mr. Charles Eugene    male   NaN      0
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1
19                            Masselmani, Mrs. Fatima  female   NaN      0

    Parch            Ticket     Fare Cabin Embarked
0       0         A/5 21171   7.2500   NaN        S
1       0          PC 17599  71.2833   C85        C
2       0  STON/O2. 3101282   7.9250   NaN        S
3       0            113803  53.1000  C123        S
4       0            373450   8.0500   NaN        S
5       0            330877   8.4583   NaN        Q
6       0             17463  51.8625   E46        S
7       1            349909  21.0750   NaN        S
8       2            347742  11.1333   NaN        S
9       0            237736  30.0708   NaN        C
10      1           PP 9549  16.7000    G6        S
11      0            113783  26.5500  C103        S
12      0         A/5. 2151   8.0500   NaN        S
13      5            347082  31.2750   NaN        S
14      0            350406   7.8542   NaN        S
15      0            248706  16.0000   NaN        S
16      1            382652  29.1250   NaN        Q
17      0            244373  13.0000   NaN        S
18      0            345763  18.0000   NaN        S
19      0              2649   7.2250   NaN        C

In [263]:
# 76
print(df.iloc[50:101])

     PassengerId  Survived  Pclass  \
50            51         0       3
51            52         0       3
52            53         1       1
53            54         1       2
54            55         0       1
55            56         1       1
56            57         1       2
57            58         0       3
58            59         1       2
59            60         0       3
60            61         0       3
61            62         1       1
62            63         0       1
63            64         0       3
64            65         0       1
65            66         1       3
66            67         1       2
67            68         0       3
68            69         1       3
69            70         0       3
70            71         0       2
71            72         0       3
72            73         0       2
73            74         0       3
74            75         1       3
75            76         0       3
76            77         0       3
77            78         0       3
78            79         1       2
79            80         1       3
80            81         0       3
81            82         1       3
82            83         1       3
83            84         0       1
84            85         1       2
85            86         1       3
86            87         0       3
87            88         0       3
88            89         1       1
89            90         0       3
90            91         0       3
91            92         0       3
92            93         0       1
93            94         0       3
94            95         0       3
95            96         0       3
96            97         0       1
97            98         1       1
98            99         1       2
99           100         0       2
100          101         0       3

                                                  Name     Sex    Age  SibSp  \
50                          Panula, Master. Juha Niilo    male   7.00      4
51                        Nosworthy, Mr. Richard Cater    male  21.00      0
52            Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.00      1
53   Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.00      1
54                      Ostby, Mr. Engelhart Cornelius    male  65.00      0
55                                   Woolner, Mr. Hugh    male    NaN      0
56                                   Rugg, Miss. Emily  female  21.00      0
57                                 Novel, Mr. Mansouer    male  28.50      0
58                        West, Miss. Constance Mirium  female   5.00      1
59                  Goodwin, Master. William Frederick    male  11.00      5
60                               Sirayanian, Mr. Orsen    male  22.00      0
61                                 Icard, Miss. Amelie  female  38.00      0
62                         Harris, Mr. Henry Birkhardt    male  45.00      1
63                               Skoog, Master. Harald    male   4.00      3
64                               Stewart, Mr. Albert A    male    NaN      0
65                            Moubarek, Master. Gerios    male    NaN      1
66                        Nye, Mrs. (Elizabeth Ramell)  female  29.00      0
67                            Crease, Mr. Ernest James    male  19.00      0
68                     Andersson, Miss. Erna Alexandra  female  17.00      4
69                                   Kink, Mr. Vincenz    male  26.00      2
70                          Jenkin, Mr. Stephen Curnow    male  32.00      0
71                          Goodwin, Miss. Lillian Amy  female  16.00      5
72                                Hood, Mr. Ambrose Jr    male  21.00      0
73                         Chronopoulos, Mr. Apostolos    male  26.00      1
74                                       Bing, Mr. Lee    male  32.00      0
75                             Moen, Mr. Sigurd Hansen    male  25.00      0
76                                   Staneff, Mr. Ivan    male    NaN      0
77                            Moutal, Mr. Rahamin Haim    male    NaN      0
78                       Caldwell, Master. Alden Gates    male   0.83      0
79                            Dowdell, Miss. Elizabeth  female  30.00      0
80                                Waelens, Mr. Achille    male  22.00      0
81                         Sheerlinck, Mr. Jan Baptist    male  29.00      0
82                      McDermott, Miss. Brigdet Delia  female    NaN      0
83                             Carrau, Mr. Francisco M    male  28.00      0
84                                 Ilett, Miss. Bertha  female  17.00      0
85   Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  female  33.00      3
86                              Ford, Mr. William Neal    male  16.00      1
87                       Slocovski, Mr. Selman Francis    male    NaN      0
88                          Fortune, Miss. Mabel Helen  female  23.00      3
89                              Celotti, Mr. Francesco    male  24.00      0
90                                Christmann, Mr. Emil    male  29.00      0
91                          Andreasson, Mr. Paul Edvin    male  20.00      0
92                         Chaffee, Mr. Herbert Fuller    male  46.00      1
93                             Dean, Mr. Bertram Frank    male  26.00      1
94                                   Coxon, Mr. Daniel    male  59.00      0
95                         Shorney, Mr. Charles Joseph    male    NaN      0
96                           Goldschmidt, Mr. George B    male  71.00      0
97                     Greenfield, Mr. William Bertram    male  23.00      0
98                Doling, Mrs. John T (Ada Julia Bone)  female  34.00      0
99                                   Kantor, Mr. Sinai    male  34.00      1
100                            Petranec, Miss. Matilda  female  28.00      0

     Parch           Ticket      Fare        Cabin Embarked
50       1          3101295   39.6875          NaN        S
51       0       A/4. 39886    7.8000          NaN        S
52       0         PC 17572   76.7292          D33        C
53       0             2926   26.0000          NaN        S
54       1           113509   61.9792          B30        C
55       0            19947   35.5000          C52        S
56       0       C.A. 31026   10.5000          NaN        S
57       0             2697    7.2292          NaN        C
58       2       C.A. 34651   27.7500          NaN        S
59       2          CA 2144   46.9000          NaN        S
60       0             2669    7.2292          NaN        C
61       0           113572   80.0000          B28      NaN
62       0            36973   83.4750          C83        S
63       2           347088   27.9000          NaN        S
64       0         PC 17605   27.7208          NaN        C
65       1             2661   15.2458          NaN        C
66       0       C.A. 29395   10.5000          F33        S
67       0        S.P. 3464    8.1583          NaN        S
68       2          3101281    7.9250          NaN        S
69       0           315151    8.6625          NaN        S
70       0       C.A. 33111   10.5000          NaN        S
71       2          CA 2144   46.9000          NaN        S
72       0     S.O.C. 14879   73.5000          NaN        S
73       0             2680   14.4542          NaN        C
74       0             1601   56.4958          NaN        S
75       0           348123    7.6500        F G73        S
76       0           349208    7.8958          NaN        S
77       0           374746    8.0500          NaN        S
78       2           248738   29.0000          NaN        S
79       0           364516   12.4750          NaN        S
80       0           345767    9.0000          NaN        S
81       0           345779    9.5000          NaN        S
82       0           330932    7.7875          NaN        Q
83       0           113059   47.1000          NaN        S
84       0       SO/C 14885   10.5000          NaN        S
85       0          3101278   15.8500          NaN        S
86       3       W./C. 6608   34.3750          NaN        S
87       0  SOTON/OQ 392086    8.0500          NaN        S
88       2            19950  263.0000  C23 C25 C27        S
89       0           343275    8.0500          NaN        S
90       0           343276    8.0500          NaN        S
91       0           347466    7.8542          NaN        S
92       0      W.E.P. 5734   61.1750          E31        S
93       2        C.A. 2315   20.5750          NaN        S
94       0           364500    7.2500          NaN        S
95       0           374910    8.0500          NaN        S
96       0         PC 17754   34.6542           A5        C
97       1         PC 17759   63.3583      D10 D12        C
98       1           231919   23.0000          NaN        S
99       0           244367   26.0000          NaN        S
100      0           349245    7.8958          NaN        S

In [264]:
# 77
print(df.iloc[10:21,2:6])

    Pclass                                               Name     Sex   Age
10       3                    Sandstrom, Miss. Marguerite Rut  female   4.0
11       1                           Bonnell, Miss. Elizabeth  female  58.0
12       3                     Saundercock, Mr. William Henry    male  20.0
13       3                        Andersson, Mr. Anders Johan    male  39.0
14       3               Vestrom, Miss. Hulda Amanda Adolfina  female  14.0
15       2                   Hewlett, Mrs. (Mary D Kingcome)   female  55.0
16       3                               Rice, Master. Eugene    male   2.0
17       2                       Williams, Mr. Charles Eugene    male   NaN
18       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0
19       3                            Masselmani, Mrs. Fatima  female   NaN
20       2                               Fynney, Mr. Joseph J    male  35.0

In [265]:
# 78
print(df.loc[:14,['Age','Fare']])

     Age     Fare
0   22.0   7.2500
1   38.0  71.2833
2   26.0   7.9250
3   35.0  53.1000
4   35.0   8.0500
5    NaN   8.4583
6   54.0  51.8625
7    2.0  21.0750
8   27.0  11.1333
9   14.0  30.0708
10   4.0  16.7000
11  58.0  26.5500
12  20.0   8.0500
13  39.0  31.2750
14  14.0   7.8542

In [266]:
# 79
print(df.loc[df["Age"] > df["Age"].mean()])

     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
4              5         0       3
6              7         0       1
11            12         1       1
..           ...       ...     ...
873          874         0       3
879          880         1       1
881          882         0       3
885          886         0       3
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
6                              McCarthy, Mr. Timothy J    male  54.0      0
11                            Bonnell, Miss. Elizabeth  female  58.0      0
..                                                 ...     ...   ...    ...
873                        Vander Cruyssen, Mr. Victor    male  47.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
881                                 Markun, Mr. Johann    male  33.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch    Ticket     Fare Cabin Embarked
1        0  PC 17599  71.2833   C85        C
3        0    113803  53.1000  C123        S
4        0    373450   8.0500   NaN        S
6        0     17463  51.8625   E46        S
11       0    113783  26.5500  C103        S
..     ...       ...      ...   ...      ...
873      0    345765   9.0000   NaN        S
879      1     11767  83.1583   C50        C
881      0    349257   7.8958   NaN        S
885      5    382652  29.1250   NaN        Q
890      0    370376   7.7500   NaN        Q

[330 rows x 12 columns]

In [267]:
# 80
print(df.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Length: 891, dtype: bool

In [268]:
# 81)
print(df.duplicated().sum())

0

In [269]:
# 82
df_no_duplicates = df.drop_duplicates()
print(df_no_duplicates.shape)

(891, 12)

In [270]:
# 83
print(df["Name"].str.upper())

0                                BRAUND, MR. OWEN HARRIS
1      CUMINGS, MRS. JOHN BRADLEY (FLORENCE BRIGGS TH...
2                                 HEIKKINEN, MISS. LAINA
3           FUTRELLE, MRS. JACQUES HEATH (LILY MAY PEEL)
4                               ALLEN, MR. WILLIAM HENRY
                             ...
886                                MONTVILA, REV. JUOZAS
887                         GRAHAM, MISS. MARGARET EDITH
888             JOHNSTON, MISS. CATHERINE HELEN "CARRIE"
889                                BEHR, MR. KARL HOWELL
890                                  DOOLEY, MR. PATRICK
Name: Name, Length: 891, dtype: str

In [271]:
# 84
print(df["Name"].str.lower())

0                                braund, mr. owen harris
1      cumings, mrs. john bradley (florence briggs th...
2                                 heikkinen, miss. laina
3           futrelle, mrs. jacques heath (lily may peel)
4                               allen, mr. william henry
                             ...
886                                montvila, rev. juozas
887                         graham, miss. margaret edith
888             johnston, miss. catherine helen "carrie"
889                                behr, mr. karl howell
890                                  dooley, mr. patrick
Name: Name, Length: 891, dtype: str

In [272]:
# 85
print(df["Name"].str.title())

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: str

In [273]:
# 86
print(df["Name"].str.len())

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Name, Length: 891, dtype: int64

In [274]:
# 87
print(df.loc[df["Name"].str.contains("Mr")])

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
3              4         1       1
4              5         0       3
5              6         0       3
..           ...       ...     ...
883          884         0       2
884          885         0       3
885          886         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
5                                     Moran, Mr. James    male   NaN      0
..                                                 ...     ...   ...    ...
883                      Banfield, Mr. Frederick James    male  28.0      0
884                             Sutehall, Mr. Henry Jr    male  25.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
5        0            330877   8.4583   NaN        Q
..     ...               ...      ...   ...      ...
883      0  C.A./SOTON 34068  10.5000   NaN        S
884      0   SOTON/OQ 392076   7.0500   NaN        S
885      5            382652  29.1250   NaN        Q
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[647 rows x 12 columns]

In [275]:
# 88
print(df.loc[df["Name"].str.contains("Mrs")])

     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
8              9         1       3
9             10         1       2
15            16         1       2
..           ...       ...     ...
871          872         1       1
874          875         1       2
879          880         1       1
880          881         1       2
885          886         0       3

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0
..                                                 ...     ...   ...    ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0

     Parch     Ticket     Fare Cabin Embarked
1        0   PC 17599  71.2833   C85        C
3        0     113803  53.1000  C123        S
8        2     347742  11.1333   NaN        S
9        0     237736  30.0708   NaN        C
15       0     248706  16.0000   NaN        S
..     ...        ...      ...   ...      ...
871      1      11751  52.5542   D35        S
874      0  P/PP 3381  24.0000   NaN        C
879      1      11767  83.1583   C50        C
880      1     230433  26.0000   NaN        S
885      5     382652  29.1250   NaN        Q

[129 rows x 12 columns]

In [276]:
# 89
print(df.loc[df["Name"].str.contains("Miss")])

     PassengerId  Survived  Pclass                                      Name  \
2              3         1       3                    Heikkinen, Miss. Laina
10            11         1       3           Sandstrom, Miss. Marguerite Rut
11            12         1       1                  Bonnell, Miss. Elizabeth
14            15         0       3      Vestrom, Miss. Hulda Amanda Adolfina
22            23         1       3               McGowan, Miss. Anna "Annie"
..           ...       ...     ...                                       ...
866          867         1       2              Duran y More, Miss. Asuncion
875          876         1       3          Najib, Miss. Adele Kiamie "Jane"
882          883         0       3              Dahlberg, Miss. Gerda Ulrika
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
10   female   4.0      1      1           PP 9549  16.7000    G6        S
11   female  58.0      0      0            113783  26.5500  C103        S
14   female  14.0      0      0            350406   7.8542   NaN        S
22   female  15.0      0      0            330923   8.0292   NaN        Q
..      ...   ...    ...    ...               ...      ...   ...      ...
866  female  27.0      1      0     SC/PARIS 2149  13.8583   NaN        C
875  female  15.0      0      0              2667   7.2250   NaN        C
882  female  22.0      0      0              7552  10.5167   NaN        S
887  female  19.0      0      0            112053  30.0000   B42        S
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S

[182 rows x 12 columns]

In [277]:
# 90
print(df.loc[df["Name"].str.startswith("A")])

     PassengerId  Survived  Pclass  \
4              5         0       3
13            14         0       3
25            26         1       3
40            41         0       3
49            50         0       3
68            69         1       3
91            92         0       3
114          115         0       3
119          120         0       3
144          145         0       2
146          147         1       3
182          183         0       3
192          193         1       3
207          208         1       3
210          211         0       3
233          234         1       3
244          245         0       3
261          262         1       3
275          276         1       1
279          280         1       3
297          298         0       1
305          306         1       1
308          309         0       2
353          354         0       3
363          364         0       3
365          366         0       3
369          370         1       1
401          402         0       3
460          461         1       1
493          494         0       1
498          499         0       1
518          519         1       2
541          542         0       3
542          543         0       3
571          572         1       1
610          611         0       3
700          701         1       1
730          731         1       1
746          747         0       3
780          781         1       3
784          785         0       3
806          807         0       1
810          811         0       3
813          814         0       3
833          834         0       3
834          835         0       3
840          841         0       3
845          846         0       3
850          851         0       3
855          856         1       3
874          875         1       2

                                                  Name     Sex    Age  SibSp  \
4                             Allen, Mr. William Henry    male  35.00      0
13                         Andersson, Mr. Anders Johan    male  39.00      1
25   Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.00      1
40      Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.00      1
49       Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.00      1
68                     Andersson, Miss. Erna Alexandra  female  17.00      4
91                          Andreasson, Mr. Paul Edvin    male  20.00      0
114                              Attalah, Miss. Malake  female  17.00      0
119                  Andersson, Miss. Ellis Anna Maria  female   2.00      4
144                         Andrew, Mr. Edgardo Samuel    male  18.00      0
146       Andersson, Mr. August Edvard ("Wennerstrom")    male  27.00      0
182              Asplund, Master. Clarence Gustaf Hugo    male   9.00      4
192    Andersen-Jensen, Miss. Carla Christine Nielsine  female  19.00      1
207                        Albimona, Mr. Nassef Cassem    male  26.00      0
210                                     Ali, Mr. Ahmed    male  24.00      0
233                     Asplund, Miss. Lillian Gertrud  female   5.00      4
244                               Attalah, Mr. Sleiman    male  30.00      0
261                  Asplund, Master. Edvin Rojj Felix    male   3.00      4
275                  Andrews, Miss. Kornelia Theodosia  female  63.00      1
279                   Abbott, Mrs. Stanton (Rosa Hunt)  female  35.00      1
297                       Allison, Miss. Helen Loraine  female   2.00      1
305                     Allison, Master. Hudson Trevor    male   0.92      1
308                                Abelson, Mr. Samuel    male  30.00      1
353                          Arnold-Franchi, Mr. Josef    male  25.00      1
363                                    Asim, Mr. Adola    male  35.00      0
365                     Adahl, Mr. Mauritz Nils Martin    male  30.00      0
369                      Aubart, Mme. Leontine Pauline  female  24.00      0
401                                    Adams, Mr. John    male  26.00      0
460                                Anderson, Mr. Harry    male  48.00      0
493                            Artagaveytia, Mr. Ramon    male  71.00      0
498    Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00      1
518  Angle, Mrs. William A (Florence "Mary" Agnes H...  female  36.00      1
541               Andersson, Miss. Ingeborg Constanzia  female   9.00      4
542                  Andersson, Miss. Sigrid Elisabeth  female  11.00      4
571      Appleton, Mrs. Edward Dale (Charlotte Lamson)  female  53.00      2
610  Andersson, Mrs. Anders Johan (Alfrida Konstant...  female  39.00      1
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  female  18.00      1
730                      Allen, Miss. Elisabeth Walton  female  29.00      0
746                        Abbott, Mr. Rossmore Edward    male  16.00      1
780                               Ayoub, Miss. Banoura  female  13.00      0
784                                   Ali, Mr. William    male  25.00      0
806                             Andrews, Mr. Thomas Jr    male  39.00      0
810                             Alexander, Mr. William    male  26.00      0
813                 Andersson, Miss. Ebba Iris Alfrida  female   6.00      4
833                             Augustsson, Mr. Albert    male  23.00      0
834                             Allum, Mr. Owen George    male  18.00      0
840                        Alhomaki, Mr. Ilmari Rudolf    male  20.00      0
845                                Abbing, Mr. Anthony    male  42.00      0
850            Andersson, Master. Sigvard Harald Elias    male   4.00      4
855                         Aks, Mrs. Sam (Leah Rosen)  female  18.00      0
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.00      1

     Parch              Ticket      Fare    Cabin Embarked
4        0              373450    8.0500      NaN        S
13       5              347082   31.2750      NaN        S
25       5              347077   31.3875      NaN        S
40       0                7546    9.4750      NaN        S
49       0              349237   17.8000      NaN        S
68       2             3101281    7.9250      NaN        S
91       0              347466    7.8542      NaN        S
114      0                2627   14.4583      NaN        C
119      2              347082   31.2750      NaN        S
144      0              231945   11.5000      NaN        S
146      0              350043    7.7958      NaN        S
182      2              347077   31.3875      NaN        S
192      0              350046    7.8542      NaN        S
207      0                2699   18.7875      NaN        C
210      0  SOTON/O.Q. 3101311    7.0500      NaN        S
233      2              347077   31.3875      NaN        S
244      0                2694    7.2250      NaN        C
261      2              347077   31.3875      NaN        S
275      0               13502   77.9583       D7        S
279      1           C.A. 2673   20.2500      NaN        S
297      2              113781  151.5500  C22 C26        S
305      2              113781  151.5500  C22 C26        S
308      0           P/PP 3381   24.0000      NaN        C
353      0              349237   17.8000      NaN        S
363      0  SOTON/O.Q. 3101310    7.0500      NaN        S
365      0              C 7076    7.2500      NaN        S
369      0            PC 17477   69.3000      B35        C
401      0              341826    8.0500      NaN        S
460      0               19952   26.5500      E12        S
493      0            PC 17609   49.5042      NaN        C
498      2              113781  151.5500  C22 C26        S
518      0              226875   26.0000      NaN        S
541      2              347082   31.2750      NaN        S
542      2              347082   31.2750      NaN        S
571      0               11769   51.4792     C101        S
610      5              347082   31.2750      NaN        S
700      0            PC 17757  227.5250  C62 C64        C
730      0               24160  211.3375       B5        S
746      1           C.A. 2673   20.2500      NaN        S
780      0                2687    7.2292      NaN        C
784      0  SOTON/O.Q. 3101312    7.0500      NaN        S
806      0              112050    0.0000      A36        S
810      0                3474    7.8875      NaN        S
813      2              347082   31.2750      NaN        S
833      0              347468    7.8542      NaN        S
834      0                2223    8.3000      NaN        S
840      0    SOTON/O2 3101287    7.9250      NaN        S
845      0           C.A. 5547    7.5500      NaN        S
850      2              347082   31.2750      NaN        S
855      1              392091    9.3500      NaN        S
874      0           P/PP 3381   24.0000      NaN        C

In [278]:
# 91
print(df.loc[df["Name"].str.endswith("n")])

     PassengerId  Survived  Pclass                           Name     Sex  \
13            14         0       3    Andersson, Mr. Anders Johan    male
23            24         1       1   Sloper, Mr. William Thompson    male
45            46         0       3       Rogers, Mr. William John    male
60            61         0       3          Sirayanian, Mr. Orsen    male
75            76         0       3        Moen, Mr. Sigurd Hansen    male
..           ...       ...     ...                            ...     ...
866          867         1       2   Duran y More, Miss. Asuncion  female
868          869         0       3    van Melkebeke, Mr. Philemon    male
870          871         0       3              Balkic, Mr. Cerin    male
876          877         0       3  Gustafsson, Mr. Alfred Ossian    male
881          882         0       3             Markun, Mr. Johann    male

      Age  SibSp  Parch           Ticket     Fare  Cabin Embarked
13   39.0      1      5           347082  31.2750    NaN        S
23   28.0      0      0           113788  35.5000     A6        S
45    NaN      0      0  S.C./A.4. 23567   8.0500    NaN        S
60   22.0      0      0             2669   7.2292    NaN        C
75   25.0      0      0           348123   7.6500  F G73        S
..    ...    ...    ...              ...      ...    ...      ...
866  27.0      1      0    SC/PARIS 2149  13.8583    NaN        C
868   NaN      0      0           345777   9.5000    NaN        S
870  26.0      0      0           349248   7.8958    NaN        S
876  20.0      0      0             7534   9.8458    NaN        S
881  33.0      0      0           349257   7.8958    NaN        S

[110 rows x 12 columns]

In [279]:
# 92
print(df["Name"].str.count("a"))

0      2
1      2
2      2
3      3
4      1
      ..
886    2
887    4
888    2
889    1
890    1
Name: Name, Length: 891, dtype: int64

In [280]:
# 93
print(df["Name"].str.replace("Mr.", "Mister", regex=False))

0                             Braund, Mister Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                            Allen, Mister William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                             Behr, Mister Karl Howell
890                               Dooley, Mister Patrick
Name: Name, Length: 891, dtype: str

In [281]:
# 94
print(df["Name"].str.replace(",", "-", regex=False))

0                                Braund- Mr. Owen Harris
1      Cumings- Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen- Miss. Laina
3           Futrelle- Mrs. Jacques Heath (Lily May Peel)
4                               Allen- Mr. William Henry
                             ...
886                                Montvila- Rev. Juozas
887                         Graham- Miss. Margaret Edith
888             Johnston- Miss. Catherine Helen "Carrie"
889                                Behr- Mr. Karl Howell
890                                  Dooley- Mr. Patrick
Name: Name, Length: 891, dtype: str

In [282]:
# 95
print(df["Name"].str.slice(0, 5))

0      Braun
1      Cumin
2      Heikk
3      Futre
4      Allen
       ...
886    Montv
887    Graha
888    Johns
889    Behr,
890    Doole
Name: Name, Length: 891, dtype: str

In [283]:
#96
print(df["Name"].str.slice(-5))

0      arris
1      ayer)
2      Laina
3      Peel)
4      Henry
       ...
886    uozas
887    Edith
888    rrie"
889    owell
890    trick
Name: Name, Length: 891, dtype: str

In [284]:
# 97
print(df["Name"].str.split(","))

0                             [Braund,  Mr. Owen Harris]
1      [Cumings,  Mrs. John Bradley (Florence Briggs ...
2                              [Heikkinen,  Miss. Laina]
3        [Futrelle,  Mrs. Jacques Heath (Lily May Peel)]
4                            [Allen,  Mr. William Henry]
                             ...
886                             [Montvila,  Rev. Juozas]
887                      [Graham,  Miss. Margaret Edith]
888          [Johnston,  Miss. Catherine Helen "Carrie"]
889                             [Behr,  Mr. Karl Howell]
890                               [Dooley,  Mr. Patrick]
Name: Name, Length: 891, dtype: object

In [285]:
# 98
df["Title"] = df["Name"].str.extract(r",\s*(Mr|Mrs|Miss|Master)\.")
print(df["Title"])

0        Mr
1       Mrs
2      Miss
3       Mrs
4        Mr
       ...
886     NaN
887    Miss
888    Miss
889      Mr
890      Mr
Name: Title, Length: 891, dtype: str

In [286]:
# 99
df["Name_Length"] = df["Name"].str.len()
print(df[["Name", "Name_Length"]])

                                                  Name  Name_Length
0                              Braund, Mr. Owen Harris           23
1    Cumings, Mrs. John Bradley (Florence Briggs Th...           51
2                               Heikkinen, Miss. Laina           22
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)           44
4                             Allen, Mr. William Henry           24
..                                                 ...          ...
886                              Montvila, Rev. Juozas           21
887                       Graham, Miss. Margaret Edith           28
888           Johnston, Miss. Catherine Helen "Carrie"           40
889                              Behr, Mr. Karl Howell           21
890                                Dooley, Mr. Patrick           19

[891 rows x 2 columns]

In [287]:
# 100
max_length = df["Name"].str.len().max()
print(df[df["Name"].str.len() == max_length])

     PassengerId  Survived  Pclass  \
307          308         1       1

                                                  Name     Sex   Age  SibSp  \
307  Penasco y Castellana, Mrs. Victor de Satode (M...  female  17.0      1

     Parch    Ticket   Fare Cabin Embarked Title  Name_Length
307      0  PC 17758  108.9   C65        C   Mrs           82