# Pandas  – Introduction, Series, DataFrame & Basic Exploration

## 1. Pandas Introduction

### What is Pandas?

Pandas is an open-source Python library used for:

- Data manipulation  
- Data analysis  
- Data cleaning  

It is mainly used in:

- Data Science  
- Machine Learning  
- Data Analysis  

Pandas works with structured/tabular data like:

- Excel spreadsheets  
- SQL tables  
- CSV files

### Why Pandas is Important

- Handles large datasets easily  
- Provides powerful data analysis functions  
- Works well with NumPy, Matplotlib, Scikit-learn  

Helps perform tasks like:

- Filtering data  
- Grouping data  
- Cleaning missing values  
- Statistical analysis

### Importing Pandas

In [1]:
import pandas as pd

`pd` is an alias used for convenience.

# 2. Pandas Series

### What is a Series?

A Pandas Series is:

- A one-dimensional labeled array
- Similar to a single column in Excel

Each value has:

- Index
- Value

Example Structure

| Index | Value |
|------|------|
|0|10|
|1|20|
|2|30|

## Ways to Create a Pandas Series

### 1. Creating an Empty Series

**Concept**

- Used when we want to initialize an empty container
- Data can be added later

In [1]:
import pandas as pd

ser = pd.Series()

print(ser)

Series([], dtype: object)

### 2. Creating Series from a List

**Concept**

- Python list values become Series values
- Pandas automatically assigns index starting from 0

In [3]:
import pandas as pd

data = ['A', 'B', 'C', 'D']

ser = pd.Series(data)

print(ser)

0    A
1    B
2    C
3    D
dtype: object

### 3. Creating Series from NumPy Array

**Concept**

- NumPy arrays are commonly used for numerical computation
- Pandas can convert NumPy arrays to Series easily

In [4]:
import numpy as np
import pandas as pd

data = np.arange(21,26)

ser = pd.Series(data)

print(ser)

0    21
1    22
2    23
3    24
4    25
dtype: int32

### 4. Creating Series from Dictionary

**Concept**

- Dictionary keys become index
- Dictionary values become data

In [5]:
import pandas as pd

data = {'A':100,'B':200,'C':300}#key value pairs

ser = pd.Series(data)

print(ser)

A    100
B    200
C    300
dtype: int64

### 5. Creating Series using NumPy Functions

**Concept**

Useful for:

- Scientific computing
- Statistical modeling
- Generating sequences of numbers

Important functions:

1. linspace() – Creates evenly spaced numbers
2. randn() – Generates random numbers from normal distribution

In [6]:
import numpy as np
import pandas as pd

data=np.linspace(1,10,5)
print(data)
ser = pd.Series(data)

print(ser)

[ 1.    3.25  5.5   7.75 10.  ]
0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64

### 6. Creating Series using range()

**Concept**

- range() generates a sequence of numbers
- Useful for creating ordered numeric data

In [7]:
import pandas as pd

ser = pd.Series(range(5,15))

print(ser)

0     5
1     6
2     7
3     8
4     9
5    10
6    11
7    12
8    13
9    14
dtype: int64

In [12]:
l=[20,30,40,50,60]
ser1=pd.Series(l)
print("series from list:")
print(ser1)


n=np.arange(101,121)
ser2=pd.Series(n)
print("series from numpy array:")
print(ser2)


d={101:"A",102:"B",103:"C",104:"D"}
ser3=pd.Series(d)
print("series from dictionary:")
print(ser3)

series from list:
0    20
1    30
2    40
3    50
4    60
dtype: int64
series from numpy array:
0     101
1     102
2     103
3     104
4     105
5     106
6     107
7     108
8     109
9     110
10    111
11    112
12    113
13    114
14    115
15    116
16    117
17    118
18    119
19    120
dtype: int32
series from dictionary:
101    A
102    B
103    C
104    D
dtype: object

### 7. Creating Series using List Comprehension

**Concept**

- List comprehension creates dynamic sequences
- Allows custom index labels

In [14]:
import pandas as pd

ser = pd.Series(range(1,20,3), index=[x for x in 'abcdefg'])

print(ser)

a     1
b     4
c     7
d    10
e    13
f    16
g    19
dtype: int64

# 3. Pandas DataFrame

### What is a DataFrame?

A DataFrame is:

- A two-dimensional table
- Consists of rows and columns

Similar to:

- Excel sheet
- SQL table

Example

| Name | Age | Salary |
|------|----|------|
|John|25|50000|
|Anna|30|60000|

## Ways to Create DataFrame

### 1. Creating an Empty DataFrame

**Concept**

- Creates a DataFrame with no data
- Useful when we want to add columns later

In [9]:
import pandas as pd

df = pd.DataFrame()

print(df)

Empty DataFrame
Columns: []
Index: []

### 2. Creating DataFrame from List

**Concept**

- Each list item becomes a row
- DataFrame will have one column

In [15]:
import pandas as pd

data = ['Apple','Orange','Banana']

df = pd.DataFrame(data)

print(df)
print(type(df))

        0
0   Apple
1  Orange
2  Banana
<class 'pandas.core.frame.DataFrame'>

### 3. Creating DataFrame from NumPy Array

**Concept**

- Each column represents a feature
- Useful for numerical datasets

In [17]:
import numpy as np
import pandas as pd

data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print("Numpy array:")
print(data)
#df = pd.DataFrame(data)
print("Data Frame")
df = pd.DataFrame(data)

print(df)

Numpy array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Data Frame
   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

### 4. Creating DataFrame from Dictionary

**Concept**

- Dictionary keys become column names
- Values become column data

In [12]:
import pandas as pd

data = {
'name':['Anu','Rahul','Meera'],
'course':['MBA','BCA','MTech'],
'score':[90,80,95]
}

df = pd.DataFrame(data)

print(df)

    name course  score
0    Anu    MBA     90
1  Rahul    BCA     80
2  Meera  MTech     95

# 4. Data Exploration Functions

In [1]:
import pandas as pd

df = pd.read_csv("nba.csv")#csv file
#read_excel
#read_json
#read_sql
#read_table 

print(df)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN

[458 rows x 9 columns]

## 1. Shape
shape returns the number of rows and columns in a DataFrame.

In [15]:
df.shape

(458, 9)

In [8]:
df.size

4122

In [5]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [3]:
df.head(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0

In [6]:
df.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.tail(8)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 2. Columns

In [16]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

## 3 info()
info() gives complete information about the dataset.

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [18]:
df.size

4122

object is a data type used to store string (text) data or mixed data types in a column.

In most cases, object means the column contains text values.

## 4. head() Method

**Concept**

- Displays first rows of dataset
- Helps quickly preview data

**Syntax**

```
DataFrame.head(n)
Series.head(n)
```

Default → 5 rows

In [19]:
print(df.head())#by default first 5 rows

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0

### Custom Rows

In [20]:
print(df.head(7))# 0->n-1

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5   Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
6  Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0

             College      Salary
0              Texas   7730337.0
1          Marquette   6796117.0
2  Boston University         NaN
3      Georgia State   1148640.0
4                NaN   5000000.0
5                NaN  12000000.0
6                LSU   1170960.0

### Head on Series

In [21]:
salary = df['Salary']
print(type(salary))
print(salary.head())

<class 'pandas.core.series.Series'>
0    7730337.0
1    6796117.0
2          NaN
3    1148640.0
4    5000000.0
Name: Salary, dtype: float64

### Head for Specific Columns

In [22]:
df1=df['Name']
print(type(df1))
df1.head(7)

<class 'pandas.core.series.Series'>

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
6    Jordan Mickey
Name: Name, dtype: object

In [23]:
df1=df[['Name','Salary']]
print(type(df1))
df1.head(7)

<class 'pandas.core.frame.DataFrame'>

            Name      Salary
0  Avery Bradley   7730337.0
1    Jae Crowder   6796117.0
2   John Holland         NaN
3    R.J. Hunter   1148640.0
4  Jonas Jerebko   5000000.0
5   Amir Johnson  12000000.0
6  Jordan Mickey   1170960.0

## sort_values()

In [24]:
df.sort_values("Age")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
226,Rashad Vaughn,Milwaukee Bucks,20.0,SG,19.0,6-6,202.0,UNLV,1733040.0
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
40,Kristaps Porzingis,New York Knicks,6.0,PF,20.0,7-3,240.0,NaN,4131720.0
401,Tyus Jones,Minnesota Timberwolves,1.0,PG,20.0,6-2,195.0,Duke,1282080.0
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
...,...,...,...,...,...,...,...,...,...
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,NaN,947726.0
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,NaN,8500000.0
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df.sort_values("Age", ascending=False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750.0
400,Kevin Garnett,Minnesota Timberwolves,21.0,PF,40.0,6-11,240.0,NaN,8500000.0
298,Tim Duncan,San Antonio Spurs,21.0,C,40.0,6-11,250.0,Wake Forest,5250000.0
261,Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4088019.0
102,Pablo Prigioni,Los Angeles Clippers,9.0,PG,39.0,6-3,185.0,NaN,947726.0
...,...,...,...,...,...,...,...,...,...
401,Tyus Jones,Minnesota Timberwolves,1.0,PG,20.0,6-2,195.0,Duke,1282080.0
60,Christian Wood,Philadelphia 76ers,35.0,PF,20.0,6-11,220.0,UNLV,525093.0
226,Rashad Vaughn,Milwaukee Bucks,20.0,SG,19.0,6-6,202.0,UNLV,1733040.0
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Head After Sorting

In [26]:
data_sorted = df.sort_values(by='Age')#
#data_sorted=df.sort_values(by='Age',ascending=False)# for sorting in descending order

print(data_sorted.head())

                   Name                    Team  Number Position   Age Height  \
226       Rashad Vaughn         Milwaukee Bucks    20.0       SG  19.0    6-6
122        Devin Booker            Phoenix Suns     1.0       SG  19.0    6-6
40   Kristaps Porzingis         New York Knicks     6.0       PF  20.0    7-3
401          Tyus Jones  Minnesota Timberwolves     1.0       PG  20.0    6-2
427     Cliff Alexander  Portland Trail Blazers    34.0       PF  20.0    6-8

     Weight   College     Salary
226   202.0      UNLV  1733040.0
122   206.0  Kentucky  2127840.0
40    240.0       NaN  4131720.0
401   195.0      Duke  1282080.0
427   240.0    Kansas   525093.0

## 5. tail() Method

**Concept**

- Displays last rows of dataset
- Useful to check end of data

**Syntax**

```
DataFrame.tail(n)
Series.tail(n)
```

Default → 5 rows

In [27]:


print(df.tail())

             Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN

        Salary
453  2433333.0
454   900000.0
455  2900000.0
456   947276.0
457        NaN

### Custom Rows

In [28]:
print(df.tail(7))

              Name       Team  Number Position   Age Height  Weight   College  \
451  Chris Johnson  Utah Jazz    23.0       SF  26.0    6-6   206.0    Dayton
452     Trey Lyles  Utah Jazz    41.0       PF  20.0   6-10   234.0  Kentucky
453   Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0    Butler
454      Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0       NaN
455   Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0       NaN
456    Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0    Kansas
457            NaN        NaN     NaN      NaN   NaN    NaN     NaN       NaN

        Salary
451   981348.0
452  2239800.0
453  2433333.0
454   900000.0
455  2900000.0
456   947276.0
457        NaN

### Tail on Series

In [29]:
salary = df['Salary']

print(salary.tail())

453    2433333.0
454     900000.0
455    2900000.0
456     947276.0
457          NaN
Name: Salary, dtype: float64

### Tail for Specific Columns

In [30]:
df[['Name','Salary']].tail()

             Name     Salary
453  Shelvin Mack  2433333.0
454     Raul Neto   900000.0
455  Tibor Pleiss  2900000.0
456   Jeff Withey   947276.0
457           NaN        NaN

### Tail After Sorting

In [31]:
data_sorted = df.sort_values(by='Age')
data_sorted = df.sort_values(by=['Age','Team'])

#data_sorted = df.sort_values(by='Age', ascending=False)
print(data_sorted.head())

                Name             Team  Number Position   Age Height  Weight  \
226    Rashad Vaughn  Milwaukee Bucks    20.0       SG  19.0    6-6   202.0
122     Devin Booker     Phoenix Suns     1.0       SG  19.0    6-6   206.0
13       James Young   Boston Celtics    13.0       SG  20.0    6-6   215.0
393  Emmanuel Mudiay   Denver Nuggets     0.0       PG  20.0    6-5   200.0
192  Stanley Johnson  Detroit Pistons     3.0       SF  20.0    6-7   245.0

      College     Salary
226      UNLV  1733040.0
122  Kentucky  2127840.0
13   Kentucky  1749840.0
393       NaN  3102240.0
192   Arizona  2841960.0

## 3. describe() Method

**Concept**

- describe() generates statistical summary of data
- Mainly used for numerical columns

**Syntax**

```
DataFrame.describe()
```

In [32]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [21]:

print(df.describe())

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   373 non-null    object
 8   Salary    446 non-null    float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB
None

### Output Explanation

| Statistic | Meaning |
|-----------|--------|
|count|Number of non-null values|
|mean|Average value|
|std|Standard deviation|
|min|Minimum value|
|25%|First quartile|
|50%|Median|
|75%|Third quartile|
|max|Maximum value|

### Custom Percentiles

In [15]:
df.describe(percentiles=[0.20,0.40,0.60,0.80])

           Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
20%      4.000000   23.000000  195.600000  9.472760e+05
40%     10.000000   25.000000  213.400000  1.938840e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
60%     18.600000   27.000000  230.000000  3.815000e+06
80%     30.000000   30.000000  245.000000  8.042895e+06
max     99.000000   40.000000  307.000000  2.500000e+07

### Describe String Columns

In [17]:
df['College'].describe()

count          373
unique         118
top       Kentucky
freq            22
Name: College, dtype: object

Output includes:

- count
- unique
- top (most frequent)
- freq

### Describe All Columns

In [18]:
df.describe(include='all')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
count,457,457,457.000000,457,457.000000,457,457.000000,373,4.460000e+02
unique,457,30,NaN,5,NaN,18,NaN,118,NaN
top,Avery Bradley,New Orleans Pelicans,NaN,SG,NaN,6-9,NaN,Kentucky,NaN
freq,1,19,NaN,102,NaN,59,NaN,22,NaN
mean,NaN,NaN,17.678337,NaN,26.938731,NaN,221.522976,NaN,4.842684e+06
std,NaN,NaN,15.966090,NaN,4.404016,NaN,26.368343,NaN,5.229238e+06
min,NaN,NaN,0.000000,NaN,19.000000,NaN,161.000000,NaN,3.088800e+04
25%,NaN,NaN,5.000000,NaN,24.000000,NaN,200.000000,NaN,1.044792e+06
50%,NaN,NaN,13.000000,NaN,26.000000,NaN,220.000000,NaN,2.839073e+06
75%,NaN,NaN,25.000000,NaN,30.000000,NaN,240.000000,NaN,6.500000e+06
max,NaN,NaN,99.000000,NaN,40.000000,NaN,307.000000,NaN,2.500000e+07

In [ ]:
print(df.describe())
print(df.describe(percentiles=[0.20,0.40,0.60,0.80]))
df['College'].describe()
df.describe(include='all')

In [22]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [23]:
df['Name']

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [25]:
df[['Name', 'Team']]

              Name            Team
0    Avery Bradley  Boston Celtics
1      Jae Crowder  Boston Celtics
2     John Holland  Boston Celtics
3      R.J. Hunter  Boston Celtics
4    Jonas Jerebko  Boston Celtics
..             ...             ...
453   Shelvin Mack       Utah Jazz
454      Raul Neto       Utah Jazz
455   Tibor Pleiss       Utah Jazz
456    Jeff Withey       Utah Jazz
457            NaN             NaN

[458 rows x 2 columns]

In [26]:
df[['Name', 'Team']].head()

            Name            Team
0  Avery Bradley  Boston Celtics
1    Jae Crowder  Boston Celtics
2   John Holland  Boston Celtics
3    R.J. Hunter  Boston Celtics
4  Jonas Jerebko  Boston Celtics

In [27]:
df[['Name', 'Team']].tail()

             Name       Team
453  Shelvin Mack  Utah Jazz
454     Raul Neto  Utah Jazz
455  Tibor Pleiss  Utah Jazz
456   Jeff Withey  Utah Jazz
457           NaN        NaN

## 4.index

In [28]:
df.index

RangeIndex(start=0, stop=458, step=1)

In [35]:
df.sort_index()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
df.sort_index(ascending=False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
...,...,...,...,...,...,...,...,...,...
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0

## unique()
Shows unique values

In [38]:
df['College'].unique()

array(['Texas', 'Marquette', 'Boston University', 'Georgia State', nan,
       'LSU', 'Gonzaga', 'Louisville', 'Oklahoma State', 'Ohio State',
       'Washington', 'Kentucky', 'North Carolina', 'Arizona',
       'Georgia Tech', 'Cincinnati', 'Miami (FL)', 'Stanford', 'Syracuse',
       'Saint Louis', 'Kansas', 'Georgetown', 'Texas A&M', 'UCLA', 'UNLV',
       'Wichita State', "Saint Joseph's", 'Notre Dame', 'Norfolk State',
       'Duke', 'Murray State', 'Tennessee State', 'Bowling Green',
       'Purdue', 'Wake Forest', 'Michigan', 'Missouri', 'USC',
       'Villanova', 'Rider', 'Utah', 'Belmont', 'Davidson', 'Vanderbilt',
       'Michigan State', 'Florida', 'Washington State', 'Arizona State',
       'Oklahoma', 'Wyoming', "St. John's", 'Maryland', 'Wisconsin',
       'Utah Valley', 'North Carolina State', 'UC Santa Barbara',
       'Baylor', 'Connecticut', 'Oregon State', 'New Mexico', 'Oregon',
       'Creighton', 'Arkansas', 'Memphis', "Saint Mary's", 'Tennessee',
       'Alabama', 'Georgia', 'Colorado', 'Boston College', 'Temple',
       'Fresno State', 'IUPUI', 'Eastern Washington', 'Western Michigan',
       'Virginia', 'Northeastern', 'Western Kentucky', 'Nevada',
       'Illinois', 'Kansas State', 'Charleston', 'Clemson',
       'Blinn College', 'Providence', 'Detroit', 'Rhode Island',
       'California', 'Cleveland State', 'Iowa State', 'Florida State',
       'Long Beach State', 'Penn State', 'Indiana', 'San Diego State',
       'Western Carolina', 'Houston', 'Xavier', 'Old Dominion',
       'Minnesota', 'Louisiana Tech', 'Bucknell', 'Pittsburgh',
       'Virginia Commonwealth', 'Harvard', 'Marshall', 'Iowa',
       'St. Bonaventure', 'Louisiana-Lafayette', 'Colorado State',
       'Virginia Tech', 'DePaul', 'Morehead State', 'Central Michigan',
       'Weber State', 'Lehigh', 'Westchester CC', 'Dayton', 'Butler'],
      dtype=object)

In [32]:
df['Team'].unique()

array(['Boston Celtics', 'Brooklyn Nets', 'New York Knicks',
       'Philadelphia 76ers', 'Toronto Raptors', 'Golden State Warriors',
       'Los Angeles Clippers', 'Los Angeles Lakers', 'Phoenix Suns',
       'Sacramento Kings', 'Chicago Bulls', 'Cleveland Cavaliers',
       'Detroit Pistons', 'Indiana Pacers', 'Milwaukee Bucks',
       'Dallas Mavericks', 'Houston Rockets', 'Memphis Grizzlies',
       'New Orleans Pelicans', 'San Antonio Spurs', 'Atlanta Hawks',
       'Charlotte Hornets', 'Miami Heat', 'Orlando Magic',
       'Washington Wizards', 'Denver Nuggets', 'Minnesota Timberwolves',
       'Oklahoma City Thunder', 'Portland Trail Blazers', 'Utah Jazz',
       nan], dtype=object)

In [33]:
df['Team'].nunique()

30

In [31]:
df['Team'].value_counts()

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Portland Trail Blazers    15
Oklahoma City Thunder     15
Denver Nuggets            15
Washington Wizards        15
Miami Heat                15
Charlotte Hornets         15
Atlanta Hawks             15
San Antonio Spurs         15
Houston Rockets           15
Dallas Mavericks          15
Indiana Pacers            15
Detroit Pistons           15
Cleveland Cavaliers       15
Chicago Bulls             15
Sacramento Kings          15
Phoenix Suns              15
Los Angeles Lakers        15
Los Angeles Clippers      15
Golden State Warriors     15
Toronto Raptors           15
Philadelphia 76ers        15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [38]:
df['Team'].unique()

array(['Boston Celtics', 'Brooklyn Nets', 'New York Knicks',
       'Philadelphia 76ers', 'Toronto Raptors', 'Golden State Warriors',
       'Los Angeles Clippers', 'Los Angeles Lakers', 'Phoenix Suns',
       'Sacramento Kings', 'Chicago Bulls', 'Cleveland Cavaliers',
       'Detroit Pistons', 'Indiana Pacers', 'Milwaukee Bucks',
       'Dallas Mavericks', 'Houston Rockets', 'Memphis Grizzlies',
       'New Orleans Pelicans', 'San Antonio Spurs', 'Atlanta Hawks',
       'Charlotte Hornets', 'Miami Heat', 'Orlando Magic',
       'Washington Wizards', 'Denver Nuggets', 'Minnesota Timberwolves',
       'Oklahoma City Thunder', 'Portland Trail Blazers', 'Utah Jazz',
       nan], dtype=object)

## nunique()
Count number of unique cities

In [30]:
df['College'].nunique()

118

## value_counts()
Count frequency of each column values

In [35]:
df['College'].value_counts()

College
Kentucky           22
Duke               20
Kansas             18
North Carolina     16
UCLA               15
                   ..
Utah Valley         1
Cleveland State     1
Iowa State          1
Florida State       1
Baylor              1
Name: count, Length: 118, dtype: int64

In [36]:
df['College'].unique()

array(['Texas', 'Marquette', 'Boston University', 'Georgia State', nan,
       'LSU', 'Gonzaga', 'Louisville', 'Oklahoma State', 'Ohio State',
       'Washington', 'Kentucky', 'North Carolina', 'Arizona',
       'Georgia Tech', 'Cincinnati', 'Miami (FL)', 'Stanford', 'Syracuse',
       'Saint Louis', 'Kansas', 'Georgetown', 'Texas A&M', 'UCLA', 'UNLV',
       'Wichita State', "Saint Joseph's", 'Notre Dame', 'Norfolk State',
       'Duke', 'Murray State', 'Tennessee State', 'Bowling Green',
       'Purdue', 'Wake Forest', 'Michigan', 'Missouri', 'USC',
       'Villanova', 'Rider', 'Utah', 'Belmont', 'Davidson', 'Vanderbilt',
       'Michigan State', 'Florida', 'Washington State', 'Arizona State',
       'Oklahoma', 'Wyoming', "St. John's", 'Maryland', 'Wisconsin',
       'Utah Valley', 'North Carolina State', 'UC Santa Barbara',
       'Baylor', 'Connecticut', 'Oregon State', 'New Mexico', 'Oregon',
       'Creighton', 'Arkansas', 'Memphis', "Saint Mary's", 'Tennessee',
       'Alabama', 'Georgia', 'Colorado', 'Boston College', 'Temple',
       'Fresno State', 'IUPUI', 'Eastern Washington', 'Western Michigan',
       'Virginia', 'Northeastern', 'Western Kentucky', 'Nevada',
       'Illinois', 'Kansas State', 'Charleston', 'Clemson',
       'Blinn College', 'Providence', 'Detroit', 'Rhode Island',
       'California', 'Cleveland State', 'Iowa State', 'Florida State',
       'Long Beach State', 'Penn State', 'Indiana', 'San Diego State',
       'Western Carolina', 'Houston', 'Xavier', 'Old Dominion',
       'Minnesota', 'Louisiana Tech', 'Bucknell', 'Pittsburgh',
       'Virginia Commonwealth', 'Harvard', 'Marshall', 'Iowa',
       'St. Bonaventure', 'Louisiana-Lafayette', 'Colorado State',
       'Virginia Tech', 'DePaul', 'Morehead State', 'Central Michigan',
       'Weber State', 'Lehigh', 'Westchester CC', 'Dayton', 'Butler'],
      dtype=object)

In [39]:
df['College'].nunique()

118

In [40]:
df['Team'].nunique()

30

In [40]:
cols=['College','Team']


for col in cols:
    print(f"unique values in {col}",df[col].unique())
    print("\n")
    print(f"no of unique values in {col}:",df[col].nunique())
    print("\n")
    print(f"frequency of values in {col}:",df[col].value_counts())
    print("\n")
    print("\n")

Unique values in College: ['Texas' 'Marquette' 'Boston University' 'Georgia State' nan 'LSU'
 'Gonzaga' 'Louisville' 'Oklahoma State' 'Ohio State' 'Washington'
 'Kentucky' 'North Carolina' 'Arizona' 'Georgia Tech' 'Cincinnati'
 'Miami (FL)' 'Stanford' 'Syracuse' 'Saint Louis' 'Kansas' 'Georgetown'
 'Texas A&M' 'UCLA' 'UNLV' 'Wichita State' "Saint Joseph's" 'Notre Dame'
 'Norfolk State' 'Duke' 'Murray State' 'Tennessee State' 'Bowling Green'
 'Purdue' 'Wake Forest' 'Michigan' 'Missouri' 'USC' 'Villanova' 'Rider'
 'Utah' 'Belmont' 'Davidson' 'Vanderbilt' 'Michigan State' 'Florida'
 'Washington State' 'Arizona State' 'Oklahoma' 'Wyoming' "St. John's"
 'Maryland' 'Wisconsin' 'Utah Valley' 'North Carolina State'
 'UC Santa Barbara' 'Baylor' 'Connecticut' 'Oregon State' 'New Mexico'
 'Oregon' 'Creighton' 'Arkansas' 'Memphis' "Saint Mary's" 'Tennessee'
 'Alabama' 'Georgia' 'Colorado' 'Boston College' 'Temple' 'Fresno State'
 'IUPUI' 'Eastern Washington' 'Western Michigan' 'Virginia' 'Northeastern'
 'Western Kentucky' 'Nevada' 'Illinois' 'Kansas State' 'Charleston'
 'Clemson' 'Blinn College' 'Providence' 'Detroit' 'Rhode Island'
 'California' 'Cleveland State' 'Iowa State' 'Florida State'
 'Long Beach State' 'Penn State' 'Indiana' 'San Diego State'
 'Western Carolina' 'Houston' 'Xavier' 'Old Dominion' 'Minnesota'
 'Louisiana Tech' 'Bucknell' 'Pittsburgh' 'Virginia Commonwealth'
 'Harvard' 'Marshall' 'Iowa' 'St. Bonaventure' 'Louisiana-Lafayette'
 'Colorado State' 'Virginia Tech' 'DePaul' 'Morehead State'
 'Central Michigan' 'Weber State' 'Lehigh' 'Westchester CC' 'Dayton'
 'Butler']


no of unique values in College: 118


frequency of values in College: College
Kentucky           22
Duke               20
Kansas             18
North Carolina     16
UCLA               15
                   ..
Utah Valley         1
Cleveland State     1
Iowa State          1
Florida State       1
Baylor              1
Name: count, Length: 118, dtype: int64




Unique values in Team: ['Boston Celtics' 'Brooklyn Nets' 'New York Knicks' 'Philadelphia 76ers'
 'Toronto Raptors' 'Golden State Warriors' 'Los Angeles Clippers'
 'Los Angeles Lakers' 'Phoenix Suns' 'Sacramento Kings' 'Chicago Bulls'
 'Cleveland Cavaliers' 'Detroit Pistons' 'Indiana Pacers'
 'Milwaukee Bucks' 'Dallas Mavericks' 'Houston Rockets'
 'Memphis Grizzlies' 'New Orleans Pelicans' 'San Antonio Spurs'
 'Atlanta Hawks' 'Charlotte Hornets' 'Miami Heat' 'Orlando Magic'
 'Washington Wizards' 'Denver Nuggets' 'Minnesota Timberwolves'
 'Oklahoma City Thunder' 'Portland Trail Blazers' 'Utah Jazz' nan]


no of unique values in Team: 30


frequency of values in Team: Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Portland Trail Blazers    15
Oklahoma City Thunder     15
Denver Nuggets            15
Washington Wizards        15
Miami Heat                15
Charlotte Hornets         15
Atlanta Hawks             15
San Antonio Spurs         15
Houston Rockets           15
Dallas Mavericks          15
Indiana Pacers            15
Detroit Pistons           15
Cleveland Cavaliers       15
Chicago Bulls             15
Sacramento Kings          15
Phoenix Suns              15
Los Angeles Lakers        15
Los Angeles Clippers      15
Golden State Warriors     15
Toronto Raptors           15
Philadelphia 76ers        15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64