# Merging & Joining in Pandas

Pandas merge() 



merge() is used to combine two DataFrames based on common columns or indexes, similar to SQL joins.

"how"	Description

inner	Only rows with matching keys in both DataFrames

left	All rows from left DataFrame + matched rows from right

right	All rows from right DataFrame + matched rows from left

outer	All rows from both DataFrames (fills missing values with NaN)

 ## Sample Data

In [6]:
import pandas as pd

df1 = pd.DataFrame({
    "EmpID": [1, 2, 3, 4],
    "Name": ["A", "B", "C", "D"],
    "DeptID": [101, 102, 103, 104]
})

df2 = pd.DataFrame({
    "DeptID": [101, 102, 105],
    "Department": ["HR", "IT", "Finance"]
})

df3 = pd.DataFrame({
    "EmpID": [1, 2, 5],
    "Salary": [50000, 60000, 70000]
})

print(df1)
print(df2)
print(df3)

   EmpID Name  DeptID
0      1    A     101
1      2    B     102
2      3    C     103
3      4    D     104
   DeptID Department
0     101         HR
1     102         IT
2     105    Finance
   EmpID  Salary
0      1   50000
1      2   60000
2      5   70000

## merge() Examples

In [2]:
# Inner Join
pd.merge(df1, df2, on="DeptID", how="inner")

   EmpID Name  DeptID Department
0      1    A     101         HR
1      2    B     102         IT

In [3]:
# Left Join
pd.merge(df1, df2, on="DeptID", how="left")

   EmpID Name  DeptID Department
0      1    A     101         HR
1      2    B     102         IT
2      3    C     103        NaN
3      4    D     104        NaN

In [4]:
# Right merge
pd.merge(df1, df2, on="DeptID", how="right")

   EmpID Name  DeptID Department
0    1.0    A     101         HR
1    2.0    B     102         IT
2    NaN  NaN     105    Finance

In [5]:
# Outer merge
pd.merge(df1, df2, on="DeptID", how="outer")

   EmpID Name  DeptID Department
0    1.0    A     101         HR
1    2.0    B     102         IT
2    3.0    C     103        NaN
3    4.0    D     104        NaN
4    NaN  NaN     105    Finance

In [7]:
# Merge on EmpID
pd.merge(df1, df3, on="EmpID", how="inner")

   EmpID Name  DeptID  Salary
0      1    A     101   50000
1      2    B     102   60000

In [18]:
 

# Merge with suffix
df = pd.merge(df1, df3, on="EmpID", how="outer", suffixes=("_october", "_november"))
print("data frame october:",df1)
print()
# print("data frame 2:",df2)
# print()
print("data frame november:",df3)
print()
print(df)

data frame october:    EmpID    Name  Salary
0      1     Anu   50000
1      2    Bala   60000
2      3  Chetan   70000

data frame november:    EmpID    Name  Salary
0      2    Bala   65000
1      3  Chetan   75000
2      4   Divya   80000

   EmpID Name_october  Salary_october Name_november  Salary_november
0      1          Anu         50000.0           NaN              NaN
1      2         Bala         60000.0          Bala          65000.0
2      3       Chetan         70000.0        Chetan          75000.0
3      4          NaN             NaN         Divya          80000.0

## join() Examples

In [ ]:
# Index-based join
df1.set_index("EmpID").join(df3.set_index("EmpID"))

In [ ]:
# Left join using join
df1.join(df3.set_index("EmpID"), on="EmpID")

In [ ]:
# Other joins
df1.join(df3.set_index("EmpID"), on="EmpID", how="inner")
df1.join(df3.set_index("EmpID"), on="EmpID", how="outer")

## concat() Examples

In [19]:
df4 = pd.DataFrame({
    "EmpID": [11, 12, 13, 14],
    "Name": ["G", "H", "K", "X"],
    "DeptID": [108, 109, 107, 108]
})
df4

   EmpID Name  DeptID
0     11    G     108
1     12    H     109
2     13    K     107
3     14    X     108

In [ ]:
# Row-wise concat
pd.concat([df1, df4])#by default axis=0

In [ ]:
# Column-wise concat
pd.concat([df1, df4], axis=1)

In [ ]:
pd.concat([df1, df4],axis=0)

In [21]:
# Ignore index
pd.concat([df1, df4], ignore_index=True)

   EmpID    Name   Salary  DeptID
0      1     Anu  50000.0     NaN
1      2    Bala  60000.0     NaN
2      3  Chetan  70000.0     NaN
3     11       G      NaN   108.0
4     12       H      NaN   109.0
5     13       K      NaN   107.0
6     14       X      NaN   108.0

In [22]:
# Keys
pd.concat([df1, df4], keys=["First", "Second"])

   EmpID    Name   Salary  DeptID
0      1     Anu  50000.0     NaN
1      2    Bala  60000.0     NaN
2      3  Chetan  70000.0     NaN
3     11       G      NaN   108.0
4     12       H      NaN   109.0
5     13       K      NaN   107.0
6     14       X      NaN   108.0