# Pandas Master Notebook – NBA Dataset

## Indexing, Filtering, Modifying & Data Cleaning

In [1]:
x='welcome to python'
x[0]

'w'

In [2]:
x[1:4]#1 to 3

'elc'

In [3]:
import pandas as pd

# Load dataset (make sure nba.csv is in your working directory)
df = pd.read_csv('nba.csv')
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [4]:
df.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.shape

(458, 9)

## 1️⃣ loc[] (Label-based indexing)

- Uses row and column labels
- Inclusive slicing
- Supports boolean filtering
- Used for meaningful indexing

Uses row labels (index) + column names

Syntax: df.loc[row_label, column_name]

End index is INCLUDED in slicing

Supports boolean filtering

Allows assignment (update values)

Can create new columns

Works well with real-world datasets

Supports multi-row and multi-column selection

Can use functions like isin(), between() inside loc

Preferred for data analysis tasks

# Basic Selection

In [6]:
# Example 1 #[] ,[[]]
df.loc[[10]]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0

In [7]:
df.loc[5, 'Name']

'Amir Johnson'

In [8]:
df.loc[0:5]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0

In [9]:
df.loc[0:5, 'Name']

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
Name: Name, dtype: object

In [10]:
df.loc[0:5, ['Name']]

            Name
0  Avery Bradley
1    Jae Crowder
2   John Holland
3    R.J. Hunter
4  Jonas Jerebko
5   Amir Johnson

In [11]:
df.loc[0:5, ['Name','Team']]

            Name            Team
0  Avery Bradley  Boston Celtics
1    Jae Crowder  Boston Celtics
2   John Holland  Boston Celtics
3    R.J. Hunter  Boston Celtics
4  Jonas Jerebko  Boston Celtics
5   Amir Johnson  Boston Celtics

# Column Selection

In [12]:
df.loc[:, ['Name','Age']]

              Name   Age
0    Avery Bradley  25.0
1      Jae Crowder  25.0
2     John Holland  27.0
3      R.J. Hunter  22.0
4    Jonas Jerebko  29.0
..             ...   ...
453   Shelvin Mack  26.0
454      Raul Neto  24.0
455   Tibor Pleiss  26.0
456    Jeff Withey  26.0
457            NaN   NaN

[458 rows x 2 columns]

In [13]:
df.loc[:, 'Name']

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [14]:
df.loc[:, 'Name':'Height']

              Name            Team  Number Position   Age Height
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10
..             ...             ...     ...      ...   ...    ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0
457            NaN             NaN     NaN      NaN   NaN    NaN

[458 rows x 6 columns]

In [15]:
df.loc[:, 'Name':'Age']

              Name            Team  Number Position   Age
0    Avery Bradley  Boston Celtics     0.0       PG  25.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0
2     John Holland  Boston Celtics    30.0       SG  27.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0
..             ...             ...     ...      ...   ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0
457            NaN             NaN     NaN      NaN   NaN

[458 rows x 5 columns]

# Multiple Rows & Columns

In [16]:
df.loc[[1,3,5], ['Name','Age']]

           Name   Age
1   Jae Crowder  25.0
3   R.J. Hunter  22.0
5  Amir Johnson  29.0

In [17]:
df.loc[10:20, ['Name','Salary']]

                       Name     Salary
10          Jared Sullinger  2569260.0
11            Isaiah Thomas  6912869.0
12              Evan Turner  3425510.0
13              James Young  1749840.0
14             Tyler Zeller  2616975.0
15         Bojan Bogdanovic  3425510.0
16             Markel Brown   845059.0
17          Wayne Ellington  1500000.0
18  Rondae Hollis-Jefferson  1335480.0
19             Jarrett Jack  6300000.0
20           Sergey Karasev  1599840.0

In [18]:
df.loc[5:15, 'Name':'Position']

                Name            Team  Number Position
5       Amir Johnson  Boston Celtics    90.0       PF
6      Jordan Mickey  Boston Celtics    55.0       PF
7       Kelly Olynyk  Boston Celtics    41.0        C
8       Terry Rozier  Boston Celtics    12.0       PG
9       Marcus Smart  Boston Celtics    36.0       PG
10   Jared Sullinger  Boston Celtics     7.0        C
11     Isaiah Thomas  Boston Celtics     4.0       PG
12       Evan Turner  Boston Celtics    11.0       SG
13       James Young  Boston Celtics    13.0       SG
14      Tyler Zeller  Boston Celtics    44.0        C
15  Bojan Bogdanovic   Brooklyn Nets    44.0       SG

# Boolean Filtering

In [19]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [20]:
df['Age'].value_counts()

Age
24.0    47
25.0    45
27.0    41
23.0    41
26.0    36
28.0    31
30.0    31
29.0    28
22.0    26
31.0    22
20.0    19
21.0    19
33.0    14
32.0    13
34.0    10
36.0    10
35.0     9
37.0     4
38.0     4
40.0     3
39.0     2
19.0     2
Name: count, dtype: int64

In [21]:
df.loc[df['Age'] > 30]
df.loc[df['Team'] == 'Phoenix Suns']
df.loc[(df['Age'] > 25) & (df['Salary'] > 5000000)]
df.loc[(df['Age'] > 30) | (df['Team'] == 'Brooklyn Nets')]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
...,...,...,...,...,...,...,...,...,...
406,Tayshaun Prince,Minnesota Timberwolves,12.0,SF,36.0,6-9,212.0,Kentucky,947276.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
415,Randy Foye,Oklahoma City Thunder,6.0,SG,32.0,6-4,213.0,Villanova,3135000.0
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0

In [22]:
df.loc[df['Age'] > 30]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,NaN,7402812.0
43,Sasha Vujacic,New York Knicks,18.0,SG,32.0,6-7,195.0,NaN,947276.0
...,...,...,...,...,...,...,...,...,...
406,Tayshaun Prince,Minnesota Timberwolves,12.0,SF,36.0,6-9,212.0,Kentucky,947276.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
415,Randy Foye,Oklahoma City Thunder,6.0,SG,32.0,6-4,213.0,Villanova,3135000.0
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0

In [23]:
df['Team'] == 'Phoenix Suns'

0      False
1      False
2      False
3      False
4      False
       ...
453    False
454    False
455    False
456    False
457    False
Name: Team, Length: 458, dtype: bool

In [24]:
df['Team'].value_counts()

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Portland Trail Blazers    15
Oklahoma City Thunder     15
Denver Nuggets            15
Washington Wizards        15
Miami Heat                15
Charlotte Hornets         15
Atlanta Hawks             15
San Antonio Spurs         15
Houston Rockets           15
Dallas Mavericks          15
Indiana Pacers            15
Detroit Pistons           15
Cleveland Cavaliers       15
Chicago Bulls             15
Sacramento Kings          15
Phoenix Suns              15
Los Angeles Lakers        15
Los Angeles Clippers      15
Golden State Warriors     15
Toronto Raptors           15
Philadelphia 76ers        15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [25]:
df1=df.loc[df['Team'] == 'Phoenix Suns']
df1

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
121,Eric Bledsoe,Phoenix Suns,2.0,PG,26.0,6-1,190.0,Kentucky,13500000.0
122,Devin Booker,Phoenix Suns,1.0,SG,19.0,6-6,206.0,Kentucky,2127840.0
123,Chase Budinger,Phoenix Suns,10.0,SF,28.0,6-7,209.0,Arizona,206192.0
124,Tyson Chandler,Phoenix Suns,4.0,C,33.0,7-1,240.0,NaN,13000000.0
125,Archie Goodwin,Phoenix Suns,20.0,SG,21.0,6-5,200.0,Kentucky,1160160.0
126,John Jenkins,Phoenix Suns,23.0,SG,25.0,6-4,215.0,Vanderbilt,981348.0
127,Brandon Knight,Phoenix Suns,3.0,PG,24.0,6-3,189.0,Kentucky,13500000.0
128,Alex Len,Phoenix Suns,21.0,C,22.0,7-1,260.0,Maryland,3807120.0
129,Jon Leuer,Phoenix Suns,30.0,PF,27.0,6-10,228.0,Wisconsin,1035000.0
130,Phil Pressey,Phoenix Suns,25.0,PG,25.0,5-11,175.0,Missouri,55722.0
131,Ronnie Price,Phoenix Suns,14.0,PG,32.0,6-2,190.0,Utah Valley,947276.0
132,Mirza Teletovic,Phoenix Suns,35.0,PF,30.0,6-9,242.0,NaN,5500000.0
133,P.J. Tucker,Phoenix Suns,17.0,SF,31.0,6-6,245.0,Texas,5500000.0
134,T.J. Warren,Phoenix Suns,12.0,SF,22.0,6-8,230.0,North Carolina State,2041080.0
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397.0

In [26]:
df1['Team'].value_counts()

Team
Phoenix Suns    15
Name: count, dtype: int64

In [27]:
df1=df.loc[df['Age'] > 30]
df1

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,NaN,7402812.0
43,Sasha Vujacic,New York Knicks,18.0,SG,32.0,6-7,195.0,NaN,947276.0
...,...,...,...,...,...,...,...,...,...
406,Tayshaun Prince,Minnesota Timberwolves,12.0,SF,36.0,6-9,212.0,Kentucky,947276.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
415,Randy Foye,Oklahoma City Thunder,6.0,SG,32.0,6-4,213.0,Villanova,3135000.0
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0

In [28]:
df1.shape

(91, 9)

In [29]:
df['Age'].unique()

array([25., 27., 22., 29., 21., 24., 20., 26., 28., 32., 23., 30., 33.,
       34., 37., 36., 31., 38., 39., 19., 35., 40., nan])

In [30]:
df['Team'].value_counts()

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Portland Trail Blazers    15
Oklahoma City Thunder     15
Denver Nuggets            15
Washington Wizards        15
Miami Heat                15
Charlotte Hornets         15
Atlanta Hawks             15
San Antonio Spurs         15
Houston Rockets           15
Dallas Mavericks          15
Indiana Pacers            15
Detroit Pistons           15
Cleveland Cavaliers       15
Chicago Bulls             15
Sacramento Kings          15
Phoenix Suns              15
Los Angeles Lakers        15
Los Angeles Clippers      15
Golden State Warriors     15
Toronto Raptors           15
Philadelphia 76ers        15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [31]:
df2=df.loc[(df['Age'] > 25) & (df['Salary'] > 5000000)]
df2

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0

In [32]:
df2['Age'].unique()

array([29., 27., 32., 28., 30., 34., 26., 31., 36., 37., 33., 35., 40.])

In [33]:
df2['Salary'].unique()

array([12000000.,  6912869.,  6300000., 19689000., 11235955.,  8000000.,
       22875000.,  7402812., 12650000.,  6500000., 13600000., 10050000.,
        6268675., 13800000., 11370786., 14260870., 11710456.,  5543725.,
       15501000.,  5675000.,  9650000., 18907726., 21468695.,  7085000.,
       25000000., 15592217.,  7000000.,  5219169., 13500000., 13000000.,
        5500000.,  6060606.,  5013559., 12403101.,  7700000.,  9500000.,
       16407500.,  7448760.,  8500000., 13400000., 20093064.,  8193029.,
       22970500., 13913044.,  6270000., 10300000., 17120106.,  6600000.,
        8333334.,  5200000., 15361500.,  5378974.,  8193030.,  6486486.,
        8229375., 15756438., 22359364.,  5158539.,  9588426., 19688000.,
        9638555.,  5464000.,  9213483., 10734586., 15514031.,  7500000.,
        5250000., 10000000., 13437500.,  5746479., 18671659.,  9756250.,
       13125306.,  6110034., 22192730., 10151612., 14783000., 20000000.,
        7900000.,  8344497., 11217391., 10449438., 14000000., 12100000.,
       20158622., 12250000., 16744218.,  6980802.,  6000000.,  5016000.,
       15409570.])

In [34]:
df3=df.loc[(df['Age'] > 30) | (df['Team'] == 'Brooklyn Nets')]
df3

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
...,...,...,...,...,...,...,...,...,...
406,Tayshaun Prince,Minnesota Timberwolves,12.0,SF,36.0,6-9,212.0,Kentucky,947276.0
413,Nick Collison,Oklahoma City Thunder,4.0,PF,35.0,6-10,255.0,Kansas,3750000.0
415,Randy Foye,Oklahoma City Thunder,6.0,SG,32.0,6-4,213.0,Villanova,3135000.0
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0

In [35]:
df3['Age'].unique()

array([27., 24., 28., 21., 32., 22., 26., 23., 25., 33., 34., 37., 36.,
       31., 38., 39., 35., 40.])

In [44]:
df['Team'].value_counts()

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Portland Trail Blazers    15
Oklahoma City Thunder     15
Denver Nuggets            15
Washington Wizards        15
Miami Heat                15
Charlotte Hornets         15
Atlanta Hawks             15
San Antonio Spurs         15
Houston Rockets           15
Dallas Mavericks          15
Indiana Pacers            15
Detroit Pistons           15
Cleveland Cavaliers       15
Chicago Bulls             15
Sacramento Kings          15
Phoenix Suns              15
Los Angeles Lakers        15
Los Angeles Clippers      15
Golden State Warriors     15
Toronto Raptors           15
Philadelphia 76ers        15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

## Advanced Conditions

In [36]:
dfa=df.loc[df['Team'].isin(['Brooklyn Nets','Portland Trail Blazers'])]
dfb=df.loc[df['Age'].between(25,30)]
dfc=df.loc[df['Salary'].isnull()]
dfd=df.loc[df['Salary'].notnull()]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [37]:
df.loc[df['Team'].isin(['Brooklyn Nets','Portland Trail Blazers'])]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0

In [41]:
dfs=df.loc[df['Age'].between(25,30)]

In [42]:
dfs['Age'].value_counts()

Age
25.0    45
27.0    41
26.0    36
28.0    31
30.0    31
29.0    28
Name: count, dtype: int64

In [39]:
df4=df.loc[df['Salary'].isnull()]
df4.shape

(12, 9)

In [43]:
df4

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,NaN
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,NaN
264,Jordan Farmar,Memphis Grizzlies,4.0,PG,29.0,6-2,180.0,UCLA,NaN
269,Ray McCallum,Memphis Grizzlies,5.0,PG,24.0,6-3,190.0,Detroit,NaN
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,NaN
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,NaN
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,NaN
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
df5=df.loc[df['Salary'].notnull()]
df5.shape

(446, 9)

# Updating Values

In [ ]:
df.loc[0, 'Salary'] = 999999
df.loc[df['Team']=='Lakers','Team'] = 'LA Lakers'
df.loc[df['Age'] > 30, 'Senior'] = 'Yes'
df.loc[df['Age'] <= 30, 'Senior'] = 'No'

In [62]:
df.loc[df['Team']=='Toronto Raptors','Team'] = 'TR'
df.shape

(458, 9)

In [63]:
df['Team'].unique()

array(['Boston Celtics', 'B', 'New York Knicks', 'Philadelphia 76ers',
       'TR', 'Golden State Warriors', 'Los Angeles Clippers',
       'Los Angeles Lakers', 'Phoenix Suns', 'Sacramento Kings',
       'Chicago Bulls', 'Cleveland Cavaliers', 'Detroit Pistons',
       'Indiana Pacers', 'Milwaukee Bucks', 'Dallas Mavericks',
       'Houston Rockets', 'Memphis Grizzlies', 'New Orleans Pelicans',
       'San Antonio Spurs', 'Atlanta Hawks', 'Charlotte Hornets',
       'Miami Heat', 'Orlando Magic', 'Washington Wizards',
       'Denver Nuggets', 'Minnesota Timberwolves',
       'Oklahoma City Thunder', 'Portland Trail Blazers', 'Utah Jazz',
       nan], dtype=object)

In [66]:
df.loc[df['Age'] > 30, 'Senior'] = 'Yes'
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,NaN
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,NaN
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,NaN
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,NaN
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,NaN
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,NaN
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,NaN
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [67]:
df.loc[df['Age'] <= 30, 'Senior'] = 'No'
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,No
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,No
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,No
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,No
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,No
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,No
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,No
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,No
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,No
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
df['Senior'].unique()

array(['No', 'Yes', nan], dtype=object)

In [48]:
df.loc[0, 'Salary'] = 999999
df.head(2)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,999999.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0

## 2️⃣ iloc[] (Position-based indexing)

- Uses integer positions
- Exclusive slicing
- Faster for numeric indexing
- Does not use labels

In [ ]:
# Example 1
df.iloc[0]
df.iloc[5, 2]
df.iloc[0, 0]

In [54]:
df.head(6)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,999999.0,No
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,No
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,No
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,No
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,No
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,No

In [53]:


df.iloc[5, 2]

90.0

In [55]:
df.iloc[0, 0]

'Avery Bradley'

## Slicing

In [ ]:
df.iloc[0:5]
df.iloc[0:5, 0:3]
df.iloc[:, 0:2]
df.iloc[5:10, :]

In [56]:
df.iloc[0:5]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,999999.0,No
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,No
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,No
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,No
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,No

In [57]:
df.iloc[0:5, 0:3]

            Name            Team  Number
0  Avery Bradley  Boston Celtics     0.0
1    Jae Crowder  Boston Celtics    99.0
2   John Holland  Boston Celtics    30.0
3    R.J. Hunter  Boston Celtics    28.0
4  Jonas Jerebko  Boston Celtics     8.0

In [58]:
df.iloc[:, 0:2]

              Name            Team
0    Avery Bradley  Boston Celtics
1      Jae Crowder  Boston Celtics
2     John Holland  Boston Celtics
3      R.J. Hunter  Boston Celtics
4    Jonas Jerebko  Boston Celtics
..             ...             ...
453   Shelvin Mack       Utah Jazz
454      Raul Neto       Utah Jazz
455   Tibor Pleiss       Utah Jazz
456    Jeff Withey       Utah Jazz
457            NaN             NaN

[458 rows x 2 columns]

In [59]:
df.iloc[5:10, :]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,No
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,No
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0,No
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0,No
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0,No

## Multiple Selection

In [ ]:
df.iloc[[1,3,5]]
df.iloc[[1,3,5], [0,2]]
df.iloc[[0,2,4], :]
df.iloc[:, [1,3,5]]

In [60]:
df.iloc[[1,3,5]]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,No
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,No
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,No

In [61]:
df.iloc[[1,3,5], [0,2]]

           Name  Number
1   Jae Crowder    99.0
3   R.J. Hunter    28.0
5  Amir Johnson    90.0

In [62]:
df.iloc[[0,2,4], :]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,999999.0,No
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,No
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,No

In [63]:
df.iloc[:, [1,3,5]]

               Team Position Height
0    Boston Celtics       PG    6-2
1    Boston Celtics       SF    6-6
2    Boston Celtics       SG    6-5
3    Boston Celtics       SG    6-5
4    Boston Celtics       PF   6-10
..              ...      ...    ...
453       Utah Jazz       PG    6-3
454       Utah Jazz       PG    6-1
455       Utah Jazz        C    7-3
456       Utah Jazz        C    7-0
457             NaN      NaN    NaN

[458 rows x 3 columns]

## Negative Indexing

In [ ]:
df.iloc[-1]
df.iloc[-5:]
df.iloc[:, -1]
df.iloc[:, -3:]
df.iloc[-5:-2:-1]

In [69]:
df.iloc[-1]

Name        NaN
Team        NaN
Number      NaN
Position    NaN
Age         NaN
Height      NaN
Weight      NaN
College     NaN
Salary      NaN
Senior      NaN
Name: 457, dtype: object

In [71]:
df.iloc[-5:]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,No
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,No
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,No
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,No
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
df.iloc[:, -1]

0       No
1       No
2       No
3       No
4       No
      ...
453     No
454     No
455     No
456     No
457    NaN
Name: Senior, Length: 458, dtype: object

In [73]:
df.iloc[:, -3:]

               College     Salary Senior
0                Texas  7730337.0     No
1            Marquette  6796117.0     No
2    Boston University        NaN     No
3        Georgia State  1148640.0     No
4                  NaN  5000000.0     No
..                 ...        ...    ...
453             Butler  2433333.0     No
454                NaN   900000.0     No
455                NaN  2900000.0     No
456             Kansas   947276.0     No
457                NaN        NaN    NaN

[458 rows x 3 columns]

In [78]:
df.iloc[-5:-12:-1]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,No
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0,No
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0,No
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0,No
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0,No
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0,No
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0,No

In [ ]:
 df.tail(10)

In [65]:
df.iloc[[-1]]

    Name Team  Number Position  Age Height  Weight College  Salary Senior
457  NaN  NaN     NaN      NaN  NaN    NaN     NaN     NaN     NaN    NaN

In [66]:
df.iloc[-3:]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,No
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,No
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df.iloc[:, -1]

0       No
1       No
2       No
3       No
4       No
      ...
453     No
454     No
455     No
456     No
457    NaN
Name: Senior, Length: 458, dtype: object

In [70]:
df.iloc[:, -3:]

               College     Salary Senior
0                Texas   999999.0     No
1            Marquette  6796117.0     No
2    Boston University        NaN     No
3        Georgia State  1148640.0     No
4                  NaN  5000000.0     No
..                 ...        ...    ...
453             Butler  2433333.0     No
454                NaN   900000.0     No
455                NaN  2900000.0     No
456             Kansas   947276.0     No
457                NaN        NaN    NaN

[458 rows x 3 columns]

## Step Slicing

In [81]:
x='Artificial Intelligence'
x[2:10]

'tificial'

In [82]:
x[2:10:2]

'tfca'

In [ ]:
df.iloc[0:10:2]
df.iloc[:, 0:5:2]
df.iloc[4:13:2,2:10:3]

In [ ]:
dfiloc[rows(start:stop:step),columns(start:stop:step)]

In [77]:
df.iloc[0:10:2]

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,999999.0,No
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,No
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,No
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,No
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0,No

In [83]:
df.iloc[:, 0:5:2]

              Name  Number   Age
0    Avery Bradley     0.0  25.0
1      Jae Crowder    99.0  25.0
2     John Holland    30.0  27.0
3      R.J. Hunter    28.0  22.0
4    Jonas Jerebko     8.0  29.0
..             ...     ...   ...
453   Shelvin Mack     8.0  26.0
454      Raul Neto    25.0  24.0
455   Tibor Pleiss    21.0  26.0
456    Jeff Withey    24.0  26.0
457            NaN     NaN   NaN

[458 rows x 3 columns]

In [84]:
df.iloc[4:13:2,2:10:3]

    Number Height     Salary
4      8.0   6-10  5000000.0
6     55.0    6-8  1170960.0
8     12.0    6-2  1824360.0
10     7.0    6-9  2569260.0
12    11.0    6-7  3425510.0

Feature	loc[]	iloc[]

Type	Label-based	Position-based

Input	Row names, column names	Integer index

Slicing	Inclusive	Exclusive

Boolean filtering	✅ Yes	❌ No

Assignment	✅ Yes	❌ Limited

Readability	High	Medium

When to Use
✅ Use loc[] when:

Working with column names

Applying conditions

Updating/modifying data

Doing real-world analysis

✅ Use iloc[] when:

Working with positions

Doing quick slicing

Dataset has no meaningful labels

## 3️⃣ Filtering Data

- Used to filter rows based on conditions
- Supports multiple conditions
- Can combine logical operators

In [ ]:
# Example 1
df[df['Age'] > 25]

In [ ]:
# Example 2
df[df['Team'] == 'Lakers']

In [ ]:
# Example 3
df[(df['Age'] > 25) & (df['Salary'] > 5000000)]

In [ ]:
# Example 4
df[(df['Age'] > 25) | (df['Team'] == 'Heat')]

In [ ]:
# Example 5
df[df['Team'].isin(['Lakers','Heat'])]

In [ ]:
# Example 6
df[df['Age'].between(20,30)]

In [ ]:
# Example 7
df.query('Age > 25')

In [ ]:
# Example 8
df.query('Team == "Lakers"')

In [ ]:
# Example 9
df[df['Salary'].notnull()]

In [ ]:
# Example 10
df[df['Salary'].isnull()]

## 4️⃣ Modifying Data

- Used to transform dataset
- Supports column operations
- Useful for feature engineering

In [ ]:
# Example 1
df['New_Salary'] = df['Salary'] * 1.1

In [ ]:
# Example 2
df['Age_plus'] = df['Age'] + 1

In [ ]:
# Example 3
df.loc[df['Team']=='Lakers','Team']='LA Lakers'

In [ ]:
# Example 4
df.rename(columns={'Name':'Player_Name'})

In [ ]:
# Example 5
df.rename(columns={'Age':'Player_Age'}, inplace=True)

In [ ]:
# Example 6
df.drop('Age', axis=1)

In [ ]:
# Example 7
df.drop(['Age','Salary'], axis=1)

In [ ]:
# Example 8
df.drop(0, axis=0)

In [ ]:
# Example 9
df.dropna()

In [ ]:
# Example 10
df.fillna(0)

## 5️⃣ Handling Missing Values

- Missing values affect analysis
- Handled using fill or drop methods

In [ ]:
df.isnull()
df.notnull()
df.isnull().sum()
df.fillna(0)
df.fillna(method='ffill')
df.fillna(method='bfill')
df['Salary'].fillna(df['Salary'].mean())
df.dropna()

In [79]:
# Example 1
df.isnull()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...
453,False,False,False,False,False,False,False,False,False,False
454,False,False,False,False,False,False,False,True,False,False
455,False,False,False,False,False,False,False,True,False,False
456,False,False,False,False,False,False,False,False,False,False
457,True,True,True,True,True,True,True,True,True,True

In [80]:
# Example 2
df.notnull()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,False,True
3,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...
453,True,True,True,True,True,True,True,True,True,True
454,True,True,True,True,True,True,True,False,True,True
455,True,True,True,True,True,True,True,False,True,True
456,True,True,True,True,True,True,True,True,True,True
457,False,False,False,False,False,False,False,False,False,False

In [81]:
# Example 3
df.isnull().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
Senior       1
dtype: int64

In [97]:
# Example 4
df.fillna(0)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,No
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,No
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0,No
3,0,0,0.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,No
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0,No
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,No
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,0,900000.0,No
455,0,0,0.0,C,26.0,7-3,256.0,0,2900000.0,No
456,0,0,0.0,C,26.0,7-0,231.0,Kansas,947276.0,No
457,0,0,0.0,0,0.0,0,0.0,0,0.0,0

In [98]:
df.loc[3,['Name','Team','Number']]=0
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,No
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,No
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,No
3,0,0,0.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,No
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,No
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,No
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,No
455,0,0,0.0,C,26.0,7-3,256.0,NaN,2900000.0,No
456,0,0,0.0,C,26.0,7-0,231.0,Kansas,947276.0,No
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
df.fillna(method='bfill')

C:\Users\Anju\AppData\Local\Temp\ipykernel_17132\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,No
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,No
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,1148640.0,No
3,0,0,0.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,No
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,LSU,5000000.0,No
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,No
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,Kansas,900000.0,No
455,0,0,0.0,C,26.0,7-3,256.0,Kansas,2900000.0,No
456,0,0,0.0,C,26.0,7-0,231.0,Kansas,947276.0,No
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
# Example 5
df.fillna(method='ffill')

C:\Users\Anju\AppData\Local\Temp\ipykernel_17132\2735953445.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,No
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,No
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,6796117.0,No
3,0,0,0.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,No
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,Georgia State,5000000.0,No
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,No
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,Butler,900000.0,No
455,0,0,0.0,C,26.0,7-3,256.0,Butler,2900000.0,No
456,0,0,0.0,C,26.0,7-0,231.0,Kansas,947276.0,No
457,0,0,0.0,C,26.0,7-0,231.0,Kansas,947276.0,No

In [88]:
df.fillna(method='bfill')

C:\Users\Anju\AppData\Local\Temp\ipykernel_17132\2831856154.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Senior
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,No
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,No
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,1148640.0,No
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,No
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,LSU,5000000.0,No
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,No
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,Kansas,900000.0,No
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,Kansas,2900000.0,No
456,0,0,0.0,C,26.0,7-0,231.0,Kansas,947276.0,No
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [113]:
# Example 6
df.fillna(method='bfill')

C:\Users\Anju\AppData\Local\Temp\ipykernel_17132\1591271956.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

     A
0  1.0
1  3.0
2  3.0

In [ ]:
# Example 7
#val=df['Salary'].mean()
df['Salary'].fillna(df['Salary'].mean())

In [116]:
dfnew=pd.read_csv('nba.csv')
dfnew.shape

(458, 9)

In [119]:
# Example 8
dfnew.dropna()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
...,...,...,...,...,...,...,...,...,...
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [121]:
# Example 9
dfnew.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[458 rows x 0 columns]

In [122]:
# Example 10
dfnew.dropna(subset=['Salary'])

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
...,...,...,...,...,...,...,...,...,...
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

## 6️⃣ Removing Duplicates

- Duplicate rows affect data quality
- Important in preprocessing

In [123]:
import pandas as pd

data = {
    "EmpID": [1, 2, 3, 2, 4, 5, 3, 6],
    "Name": ["Alice", "Bob", "Charlie", "Bob", "David", "Eve", "Charlie", "Frank"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "IT", "Finance", "HR"],
    "Salary": [50000, 60000, 70000, 60000, 50000, 65000, 70000, 55000]
}

df = pd.DataFrame(data)
print(df)

   EmpID     Name Department  Salary
0      1    Alice         HR   50000
1      2      Bob         IT   60000
2      3  Charlie    Finance   70000
3      2      Bob         IT   60000
4      4    David         HR   50000
5      5      Eve         IT   65000
6      3  Charlie    Finance   70000
7      6    Frank         HR   55000

In [124]:
# Example 1
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
dtype: bool

In [ ]:
df.duplicated().sum()

In [129]:
# Example 2
# df.duplicated().sum()
# df.drop_duplicates()
# df.drop_duplicates(keep='first')
# df.drop_duplicates(keep='last')
# df.drop_duplicates(subset=['Department'])
# df.drop_duplicates(subset=['Department', 'Salary'])

In [126]:
# Example 3
df.drop_duplicates()

   EmpID     Name Department  Salary
0      1    Alice         HR   50000
1      2      Bob         IT   60000
2      3  Charlie    Finance   70000
4      4    David         HR   50000
5      5      Eve         IT   65000
7      6    Frank         HR   55000

In [127]:
# Example 4
df.drop_duplicates(keep='first')

   EmpID     Name Department  Salary
0      1    Alice         HR   50000
1      2      Bob         IT   60000
2      3  Charlie    Finance   70000
4      4    David         HR   50000
5      5      Eve         IT   65000
7      6    Frank         HR   55000

In [128]:
# Example 5
df.drop_duplicates(keep='last')

   EmpID     Name Department  Salary
0      1    Alice         HR   50000
3      2      Bob         IT   60000
4      4    David         HR   50000
5      5      Eve         IT   65000
6      3  Charlie    Finance   70000
7      6    Frank         HR   55000

In [ ]:
# Example 6
df.drop_duplicates(subset=['Department'])

In [ ]:
# Example 7
df.drop_duplicates(subset=['Department', 'Salary'])

In [ ]:
# Example 8
df[df.duplicated()]

In [ ]:
# Example 9
df.drop_duplicates(inplace=True)
df

In [1]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Score": [85, 90, 95, 88, 92]
}

df = pd.DataFrame(data)
print(df)

      Name  Score
0    Alice     85
1      Bob     90
2  Charlie     95
3    David     88
4      Eve     92

In [2]:
df = df.drop([1, 3])   # remove Bob and David
print(df)

      Name  Score
0    Alice     85
2  Charlie     95
4      Eve     92

In [ ]:
# Example 10
df.reset_index(drop=True)

In [110]:
import pandas as pd

df = pd.DataFrame({'A': [1, None, 3]})
print(df)
#df = df.fillna(0)
#print(df)
df = df.bfill()

print(df)

     A
0  1.0
1  NaN
2  3.0
     A
0  1.0
1  3.0
2  3.0