## 1. Selecting Columns

In [3]:
import pandas as pd
df=pd.read_csv('nba.csv')

In [4]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

## 1. Selecting Columns

In [5]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary'],
      dtype='object')

In [6]:
df["Name"]

0      Avery Bradley
1        Jae Crowder
2       John Holland
3        R.J. Hunter
4      Jonas Jerebko
           ...
453     Shelvin Mack
454        Raul Neto
455     Tibor Pleiss
456      Jeff Withey
457              NaN
Name: Name, Length: 458, dtype: object

In [7]:
df1=df[["Name", "Salary"]]
df1

              Name     Salary
0    Avery Bradley  7730337.0
1      Jae Crowder  6796117.0
2     John Holland        NaN
3      R.J. Hunter  1148640.0
4    Jonas Jerebko  5000000.0
..             ...        ...
453   Shelvin Mack  2433333.0
454      Raul Neto   900000.0
455   Tibor Pleiss  2900000.0
456    Jeff Withey   947276.0
457            NaN        NaN

[458 rows x 2 columns]

## 2. Adding New Columns

## Add Constant Column

In [8]:
df["Experience"] = 2

In [9]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2

## Add Calculated Column

In [10]:
df["Salary_after_bonus"] = df["Salary"] * 1.10
df

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0
...,...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2,2676666.3
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,2,990000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,2,3190000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,2,1042003.6
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN

In [11]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0

## Deleting Columns

In [12]:
df2=df.drop("Experience", axis=1)
df2

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,5500000.0
...,...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0,2676666.3
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0,990000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0,3190000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,1042003.6
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#df.drop("Experience", axis=1,inplace=True)
#df=df.drop("Experience", axis=1)

In [14]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Experience,Salary_after_bonus
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,2,8503370.7
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,2,7475728.7
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,2,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,2,1263504.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,2,5500000.0

In [15]:
df3=df2.drop("Salary_after_bonus", axis=1)
df3

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Adding Rows

In [16]:
new_row = {
    "Name": "Emma",
    "Team":"Boston Celtics",
    "Number":99.0,
    "Position": "SG",
    "Age":25,
    "Height":"6-10",
    "Weight":231.0,
    "College":"Butler",
    
    "Salary":900000
}

new_df = pd.DataFrame([new_row])

print(new_df)
print("*****************************")
print()
#df4 = pd.concat([df3, new_df])
df4 = pd.concat([df3, new_df], ignore_index=True)
print(df4)

   Name            Team  Number Position  Age Height  Weight College  Salary
0  Emma  Boston Celtics    99.0       SG   25   6-10   231.0  Butler  900000
*****************************

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN
458             Butler   900000.0

[459 rows x 9 columns]

pd.concat():Combines two DataFrames.

ignore_index=True:Creates a new sequential index.

## Deleting Rows

• Missing values
• Incorrect data
• Outliers

Rows can be removed using drop().

In [17]:
df4.drop(2, inplace=True)

print(df4)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
..             ...             ...     ...      ...   ...    ...     ...
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

           College      Salary
0            Texas   7730337.0
1        Marquette   6796117.0
3    Georgia State   1148640.0
4              NaN   5000000.0
5              NaN  12000000.0
..             ...         ...
454            NaN    900000.0
455            NaN   2900000.0
456         Kansas    947276.0
457            NaN         NaN
458         Butler    900000.0

[458 rows x 9 columns]

In [18]:
df4.drop(457, inplace=True)

print(df4)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

           College      Salary
0            Texas   7730337.0
1        Marquette   6796117.0
3    Georgia State   1148640.0
4              NaN   5000000.0
5              NaN  12000000.0
..             ...         ...
453         Butler   2433333.0
454            NaN    900000.0
455            NaN   2900000.0
456         Kansas    947276.0
458         Butler    900000.0

[457 rows x 9 columns]

In [25]:
df4.drop(1, inplace=True)

print(df4)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
5     Amir Johnson  Boston Celtics    90.0       PF  29.0    6-9   240.0
6    Jordan Mickey  Boston Celtics    55.0       PF  21.0    6-8   235.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
458           Emma  Boston Celtics    99.0       SG  25.0   6-10   231.0

           College      Salary
0            Texas   7730337.0
3    Georgia State   1148640.0
4              NaN   5000000.0
5              NaN  12000000.0
6              LSU   1170960.0
..             ...         ...
453         Butler   2433333.0
454            NaN    900000.0
455            NaN   2900000.0
456         Kansas    947276.0
458         Butler    900000.0

[455 rows x 9 columns]

In [29]:
df4.reset_index(drop=True)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
2,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
3,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
4,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
...,...,...,...,...,...,...,...,...,...
450,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
451,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
452,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
453,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
454,Emma,Boston Celtics,99.0,SG,25.0,6-10,231.0,Butler,900000.0

In [32]:
# df4.drop(1, inplace=True)
# df4.reset_index(drop=True)

In [33]:
#df4.drop(1, inplace=True).reset_index(drop=True)

## loc[] and iloc[] in Pandas
Why loc and iloc are Important

In Data Science we often need to:

• select specific rows
• select specific columns
• filter data
• slice datasets

Pandas provides two powerful indexing methods:

1️⃣ .loc[] → Label-based indexing
2️⃣ .iloc[] → Position-based indexing

In [35]:
#1. Import Pandas
import pandas as pd
#2. Create Sample Dataset
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [40000, 50000, 45000, 52000, 48000]
}

df = pd.DataFrame(data)

print(df)

      Name  Age Department  Salary
0    Alice   23         HR   40000
1      Bob   25         IT   50000
2  Charlie   22    Finance   45000
3    David   24         IT   52000
4     Emma   26  Marketing   48000

3. What is loc[] ?

.loc[] selects data using row labels and column labels.

Syntax
df.loc[row_label, column_label]

Example structure

df.loc[rows , columns]

In [49]:
#4. Selecting Single Row using loc
df.loc[[2]]

      Name  Age Department  Salary
2  Charlie   22    Finance   45000

In [58]:

#5. Selecting Multiple Rows
df.loc[[1,3]]

    Name  Age Department  Salary
1    Bob   25         IT   50000
3  David   24         IT   52000

In [40]:
#6. Selecting Row and Column
df.loc[2, "Name"]

'Charlie'

In [41]:
#7. Selecting Multiple Columns
df.loc[2, ["Name", "Salary"]]

Name      Charlie
Salary      45000
Name: 2, dtype: object

In [42]:
#8. Selecting Multiple Rows and Columns
df.loc[[1,3], ["Name", "Department"]]

    Name Department
1    Bob         IT
3  David         IT

In [47]:
#9. Row Slicing using loc

#Important rule:

#loc includes the end index
df.loc[1:3]

      Name  Age Department  Salary
1      Bob   25         IT   50000
2  Charlie   22    Finance   45000
3    David   24         IT   52000

In [53]:
#10. Conditional Selection using loc


#Example: Salary greater than 45000

df.loc[df["Salary"] > 45000]


#df["Salary"] > 45000

    Name  Age Department  Salary
1    Bob   25         IT   50000
3  David   24         IT   52000
4   Emma   26  Marketing   48000

In [54]:
#11. Selecting Specific Columns with Condition
df.loc[df["Salary"] > 45000, ["Name", "Salary"]]

    Name  Salary
1    Bob   50000
3  David   52000
4   Emma   48000

In [56]:
#12. Updating Values using loc
df.loc[2, "Salary"] = 47000

df

      Name  Age Department  Salary
0    Alice   23         HR   40000
1      Bob   25         IT   50000
2  Charlie   22    Finance   47000
3    David   24         IT   52000
4     Emma   26  Marketing   48000

In [60]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [40000, 50000, 45000, 52000, 48000]
}

df = pd.DataFrame(data,index=[1,2,3,4,5])



print(df)

      Name  Age Department  Salary
1    Alice   23         HR   40000
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000
5     Emma   26  Marketing   48000

In [61]:
df.loc[1]

Name          Alice
Age              23
Department       HR
Salary        40000
Name: 1, dtype: object

In [62]:
df.iloc[1]

Name            Bob
Age              25
Department       IT
Salary        50000
Name: 2, dtype: object

In [63]:
df.loc[1:4]

      Name  Age Department  Salary
1    Alice   23         HR   40000
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000

In [64]:
df.iloc[1:4]

      Name  Age Department  Salary
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000

In [ ]:
#13. What is iloc[] ?


#.iloc[] selects data using integer positions (index numbers).

#Syntax
#df.iloc[row_position, column_position]

In [65]:
#14. Selecting Single Row using iloc
df.iloc[2]

#Returns row at position 2.

Name          Charlie
Age                22
Department    Finance
Salary          45000
Name: 3, dtype: object

In [67]:
#15. Selecting Multiple Rows
df.iloc[[1,3]]

    Name  Age Department  Salary
2    Bob   25         IT   50000
4  David   24         IT   52000

In [68]:
#16. Selecting Row and Column
df.iloc[2,1]

#Explanation

#Row → position 2
#Column → position 1

22

In [69]:
#17. Selecting Multiple Columns
df.iloc[2, [0,3]]

Name      Charlie
Salary      45000
Name: 3, dtype: object

In [ ]:
#18. Selecting Multiple Rows and Columns
df.iloc[[1,3], [0,2]]

In [70]:
#19. Row Slicing using iloc

#Important rule:

#iloc excludes the end index
df.iloc[1:4]

      Name  Age Department  Salary
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000

In [71]:
#20. Column Slicing
df.iloc[:, 1:3]

   Age Department
1   23         HR
2   25         IT
3   22    Finance
4   24         IT
5   26  Marketing

In [72]:

#21. Selecting Entire Column
df.iloc[:,1]

1    23
2    25
3    22
4    24
5    26
Name: Age, dtype: int64

Difference Between loc and iloc

Feature	loc	        iloc

Type	Label based	Position based

Input	Index name	Integer position

Range	End included	End excluded

Usage	Filtering	Numerical indexing

In [ ]:
#df.rename(columns={'old_name':'new_name'}, inplace=True)

In [ ]:
#Task:
#create a dataframe from this dictionary
#check shape and info
#display first 2 rows and last 2 rows
#check statitical summary
#Sort based on salary
#create a new column City with constant value 'NewJersy'
#create a calculated column revised salary = salary+2000
#create a new row with another persons details for IT department
#check value counts for Department
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Age": [23, 25, 22, 24, 26],
    "Department": ["HR", "IT", "Finance", "IT", "Marketing"],
    "Salary": [40000, 50000, 45000, 52000, 48000]
}

In [ ]:
df=pd.DataFrame(data)
df

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.head(2)

In [ ]:
df.tail(2)

In [ ]:
#practice task
import pandas as pd

data = {
    "Name": ["A", "B", "C", "D", "E", "F"],
    "Age": [23, 45, 31, 22, 35, 28],
    "Salary": [40000, 80000, 50000, 30000, 90000, 60000],
    "Department": ["HR", "IT", "Finance", "HR", "IT", "Finance"]
}

df = pd.DataFrame(data)

# custom index
df.index = ["emp1", "emp2", "emp3", "emp4", "emp5", "emp6"]

print(df)

In [ ]:
# df.iloc[0:3]
# df.iloc[2:5, 1:3]
# df.iloc[:, 0:2]
# df.iloc[::2]
# df.iloc[::-1]
# df.loc["emp1":"emp3"]
# df.loc["emp2":"emp5", "Name":"Salary"]
# df.loc[:, "Age":"Department"]
# df.loc["emp3":, :]
# df.loc["emp2":"emp4", "Salary"]