# Pandas GroupBy

👉 Splits data into groups
Based on one or more columns (e.g., Department, Category)

👉 Applies operations on each group
Like sum, mean, count, max, min, etc.

👉 Combines results into a new structure
Returns a summarized DataFrame/Series

## Sample Data

In [1]:
import pandas as pd

data = {
    "Department": ["HR", "IT", "IT", "HR", "Finance", "IT", "Finance"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [40000, 60000, 65000, 45000, 70000, 62000, 72000],
    "Experience": [2, 5, 6, 3, 8, 4, 9],
    "City":["Bangalore","Chennai","Kochi","Kochi","Chennai","Kochi","Mumbai"]
}

df = pd.DataFrame(data)
df

  Department Employee  Salary  Experience       City
0         HR        A   40000           2  Bangalore
1         IT        B   60000           5    Chennai
2         IT        C   65000           6      Kochi
3         HR        D   45000           3      Kochi
4    Finance        E   70000           8    Chennai
5         IT        F   62000           4      Kochi
6    Finance        G   72000           9     Mumbai

In [8]:
# df.groupby("Department")["Salary"].mean()
# df.groupby("Department")["Salary"].sum()
# df.groupby("Department")["Salary"].max()
# df.groupby("Department")["Salary"].min()
# df.groupby("Department")["Employee"].count()
# df.groupby("City")["Employee"].count()

#average, maximum and minimum salary in each department
# df.groupby("Department")["Salary"].agg(["mean", "max", "min"])
# df.groupby("Department").agg({
#     "Salary": ["mean", "max"],
#     "Experience": ["min", "max"]
# })

# df.groupby("Department").agg(
#     Average_Salary=("Salary","mean"),
#     Maximum_Salary=("Salary","max"),
# Maximum_Experience=("Experience","max"),
# Minimum_Experience=("Experience","min"),
# )

# df1.groupby(["Department", "Experience"])["Salary"].mean().reset_index()

# df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")
# df

## Basic groupby

In [2]:
df.groupby("Department")["Salary"].mean()

Department
Finance    71000.000000
HR         42500.000000
IT         62333.333333
Name: Salary, dtype: float64

In [3]:
df.groupby("Department")["Salary"].sum()

Department
Finance    142000
HR          85000
IT         187000
Name: Salary, dtype: int64

In [4]:
df.groupby("Department")['Salary'].max()

Department
Finance    72000
HR         45000
IT         65000
Name: Salary, dtype: int64

In [5]:
df.groupby("Department")['Salary'].min()

Department
Finance    70000
HR         40000
IT         60000
Name: Salary, dtype: int64

In [6]:
df.groupby("Department")['Employee'].count()

Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

In [7]:
df.groupby('City')['Employee'].count()

City
Bangalore    1
Chennai      2
Kochi        3
Mumbai       1
Name: Employee, dtype: int64

## Aggregations using agg()

In [11]:
#average, maximum and minimum salary in each department
df.groupby("Department")["Salary"].agg(["mean", "max", "min"])

                    mean    max    min
Department
Finance     71000.000000  72000  70000
HR          42500.000000  45000  40000
IT          62333.333333  65000  60000

In [12]:
#maximum and minimum experience in each department
df.groupby('Department')['Experience'].agg(['max','min'])

            max  min
Department
Finance       9    8
HR            3    2
IT            6    4

## Aggregations using agg() multiple columns

In [13]:
df.groupby("Department").agg({
    "Salary": ["mean", "max"],
    "Experience": ["min", "max"]
})

                  Salary        Experience
                    mean    max        min max
Department
Finance     71000.000000  72000          8   9
HR          42500.000000  45000          2   3
IT          62333.333333  65000          4   6

## Named Aggregations

In [16]:
df.groupby("Department").agg(
    Average_Salary=("Salary","mean"),
    Maximum_Salary=("Salary","max"),
Maximum_Experience=("Experience","max"),
Minimum_Experience=("Experience","min"),
)

,Average_Salary,Maximum_Salary,Maximum_Experience,Minimum_Experience
Department,,,,
Finance,71000.000000,72000,9,8
HR,42500.000000,45000,3,2
IT,62333.333333,65000,6,4

In [17]:
df.groupby("Department").agg(
    avg_salary=("Salary", "mean"),
    max_exp=("Experience", "max"),
    total_emp=("Employee", "count")
)

              avg_salary  max_exp  total_emp
Department
Finance     71000.000000        9          2
HR          42500.000000        3          2
IT          62333.333333        6          3

In [18]:
data = {
    "Department": ["HR", "IT", "IT", "HR", "Finance", "IT", "Finance"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [40000, 60000, 65000, 45000, 70000, 62000, 72000],
    "Experience": [2, 5, 6, 2, 8, 4, 8],
    "City":["Bangalore","Chennai","Kochi","Kochi","Chennai","Kochi","Mumbai"]
}

df1 = pd.DataFrame(data)
df1

  Department Employee  Salary  Experience       City
0         HR        A   40000           2  Bangalore
1         IT        B   60000           5    Chennai
2         IT        C   65000           6      Kochi
3         HR        D   45000           2      Kochi
4    Finance        E   70000           8    Chennai
5         IT        F   62000           4      Kochi
6    Finance        G   72000           8     Mumbai

## GroupBy with Multiple Columns

In [21]:
df1.groupby(["Department", "Experience"])["Salary"].mean().reset_index()

  Department  Experience   Salary
0    Finance           8  71000.0
1         HR           2  42500.0
2         IT           4  62000.0
3         IT           5  60000.0
4         IT           6  65000.0

## Transform
👉 Applies a function to each group

👉 Returns output with the SAME SIZE as original data

👉 Broadcasts group results back to each row

In [ ]:
df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")
df["Salary_Diff"] = df["Salary"] - df["Dept_Avg_Salary"]
df["Salary_Percent"] = df["Salary"] / df.groupby("Department")["Salary"].transform("sum")
df

In [22]:
df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")
df

  Department Employee  Salary  Experience       City  Dept_Avg_Salary
0         HR        A   40000           2  Bangalore     42500.000000
1         IT        B   60000           5    Chennai     62333.333333
2         IT        C   65000           6      Kochi     62333.333333
3         HR        D   45000           3      Kochi     42500.000000
4    Finance        E   70000           8    Chennai     71000.000000
5         IT        F   62000           4      Kochi     62333.333333
6    Finance        G   72000           9     Mumbai     71000.000000

## Apply

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Numbers": [1, 2, 3, 4]
})

df["Square"] = df["Numbers"].apply(lambda x: x**2)
print(df)

## Practice Tasks

### Beginner
- Average salary per department
- Count employees per department

### Intermediate
- Max salary per department
- Department with highest average salary

### Advanced
- Salary difference from department mean
- Top 2 employees per department
- Custom salary spread function