In [1]:
import pandas as pd

data = {
"Department": ["HR", "IT", "IT", "HR", "Finance", "IT", "Finance"],
"Employee": ["A", "B", "C", "D", "E", "F", "G"],
"Salary": [40000, 60000, 65000, 45000, 70000, 62000, 72000],
"Experience": [2, 5, 6, 3, 8, 4, 9],
"City":["Bangalore","Chennai","Kochi","Kochi","Chennai","Kochi","Mumbai"]
}

df = pd.DataFrame(data)
df

  Department Employee  Salary  Experience       City
0         HR        A   40000           2  Bangalore
1         IT        B   60000           5    Chennai
2         IT        C   65000           6      Kochi
3         HR        D   45000           3      Kochi
4    Finance        E   70000           8    Chennai
5         IT        F   62000           4      Kochi
6    Finance        G   72000           9     Mumbai

In [2]:
df.groupby("Department")["Salary"].mean()

City
Bangalore    1
Chennai      2
Kochi        3
Mumbai       1
Name: Employee, dtype: int64

In [3]:
df.groupby("Department")["Salary"].sum()

Department
Finance    142000
HR          85000
IT         187000
Name: Salary, dtype: int64

In [4]:
df.groupby("Department")["Salary"].max()

Department
Finance    72000
HR         45000
IT         65000
Name: Salary, dtype: int64

In [5]:
df.groupby("Department")["Salary"].min()

Department
Finance    70000
HR         40000
IT         60000
Name: Salary, dtype: int64

In [6]:
df.groupby("Department")["Employee"].count()

Department
Finance    2
HR         2
IT         3
Name: Employee, dtype: int64

In [7]:
df.groupby("City")["Employee"].count()

City
Bangalore    1
Chennai      2
Kochi        3
Mumbai       1
Name: Employee, dtype: int64

In [11]:
df.groupby("Department")["Salary"].agg(["mean","max","min"])

                    mean    max    min
Department
Finance     71000.000000  72000  70000
HR          42500.000000  45000  40000
IT          62333.333333  65000  60000

In [12]:
df.groupby("Department")["Experience"].agg(["max","min"])

            max  min
Department
Finance       9    8
HR            3    2
IT            6    4

In [15]:
df.groupby("Department").agg({"Salary":["mean","max"],"Experience":["min","max"]})

                  Salary        Experience
                    mean    max        min max
Department
Finance     71000.000000  72000          8   9
HR          42500.000000  45000          2   3
IT          62333.333333  65000          4   6

In [19]:
df.groupby("Department").agg(Avg_salary=("Salary","mean"),
                            Max_Salary = ("Salary","max"),
                            Min_Exp = ("Experience","min"),
                            Max_Exp = ("Experience","max"))

              Avg_salary  Max_Salary  Min_Exp  Max_Exp
Department
Finance     71000.000000       72000        8        9
HR          42500.000000       45000        2        3
IT          62333.333333       65000        4        6

In [20]:
df.groupby("Department").agg(avg_salary =("Salary","mean"),max_exp=("Experience","max"),total_emp=("Employee","count"))

              avg_salary  max_exp  total_emp
Department
Finance     71000.000000        9          2
HR          42500.000000        3          2
IT          62333.333333        6          3

In [24]:
df.groupby(["Department","Experience"])["Salary"].mean().reset_index()

  Department  Experience   Salary
0    Finance           8  70000.0
1    Finance           9  72000.0
2         HR           2  40000.0
3         HR           3  45000.0
4         IT           4  62000.0
5         IT           5  60000.0
6         IT           6  65000.0

In [37]:
data = {
"Department": ["HR", "IT", "IT", "HR", "Finance", "IT", "Finance"],
"Employee": ["A", "B", "C", "D", "E", "F", "G"],
"Salary": [40000, 60000, 65000, 45000, 70000, 62000, 72000],
"Experience": [2, 5, 6, 2, 8, 4, 8],
"City":["Bangalore","Chennai","Kochi","Kochi","Chennai","Kochi","Mumbai"]
}

df1 = pd.DataFrame(data)
df1

  Department Employee  Salary  Experience       City
0         HR        A   40000           2  Bangalore
1         IT        B   60000           5    Chennai
2         IT        C   65000           6      Kochi
3         HR        D   45000           2      Kochi
4    Finance        E   70000           8    Chennai
5         IT        F   62000           4      Kochi
6    Finance        G   72000           8     Mumbai

In [42]:
df1["Dept_avg_salary"] = df1.groupby("Department")["Salary"].transform("mean")
print(df1)

  Department Employee  Salary  Experience       City  Dept_avg_salary
0         HR        A   40000           2  Bangalore     42500.000000
1         IT        B   60000           5    Chennai     62333.333333
2         IT        C   65000           6      Kochi     62333.333333
3         HR        D   45000           2      Kochi     42500.000000
4    Finance        E   70000           8    Chennai     71000.000000
5         IT        F   62000           4      Kochi     62333.333333
6    Finance        G   72000           8     Mumbai     71000.000000

In [44]:
df1["Salary_dif"] = df1["Salary"] - df1["Dept_avg_salary"]
df

  Department Employee  Salary  Experience       City  Dept_avg_salary
0         HR        A   40000           2  Bangalore     42500.000000
1         IT        B   60000           5    Chennai     62333.333333
2         IT        C   65000           6      Kochi     62333.333333
3         HR        D   45000           3      Kochi     42500.000000
4    Finance        E   70000           8    Chennai     71000.000000
5         IT        F   62000           4      Kochi     62333.333333
6    Finance        G   72000           9     Mumbai     71000.000000

In [43]:
df1["salary_percent"] = df1["Salary"]/df1.groupby("Department")["Salary"].transform("sum")
df

  Department Employee  Salary  Experience       City  Dept_avg_salary
0         HR        A   40000           2  Bangalore     42500.000000
1         IT        B   60000           5    Chennai     62333.333333
2         IT        C   65000           6      Kochi     62333.333333
3         HR        D   45000           3      Kochi     42500.000000
4    Finance        E   70000           8    Chennai     71000.000000
5         IT        F   62000           4      Kochi     62333.333333
6    Finance        G   72000           9     Mumbai     71000.000000

In [45]:
df["dept_avg_salary"] = df1.["Salary"]/df1.groupby("Department")["Salary"]

SyntaxError: invalid syntax (4018973497.py, line 1)

In [46]:
df1["Square_of_Exp"] = df1["Experience"].apply(lambda x:x**2)
df1

,Department,Employee,Salary,Experience,City,Dept_avg_salary,salary_percent,Salary_dif,Square_of_Exp
0,HR,A,40000,2,Bangalore,42500.000000,0.470588,-2500.000000,4
1,IT,B,60000,5,Chennai,62333.333333,0.320856,-2333.333333,25
2,IT,C,65000,6,Kochi,62333.333333,0.347594,2666.666667,36
3,HR,D,45000,2,Kochi,42500.000000,0.529412,2500.000000,4
4,Finance,E,70000,8,Chennai,71000.000000,0.492958,-1000.000000,64
5,IT,F,62000,4,Kochi,62333.333333,0.331551,-333.333333,16
6,Finance,G,72000,8,Mumbai,71000.000000,0.507042,1000.000000,64

In [53]:
df.groupby("Department")["Salary"].mean()

  Department Employee  Salary  Experience       City  Dept_avg_salary
0         HR        A   40000           2  Bangalore     42500.000000
1         IT        B   60000           5    Chennai     62333.333333
2         IT        C   65000           6      Kochi     62333.333333
3         HR        D   45000           3      Kochi     42500.000000
4    Finance        E   70000           8    Chennai     71000.000000
5         IT        F   62000           4      Kochi     62333.333333
6    Finance        G   72000           9     Mumbai     71000.000000

In [55]:
df1.rename(columns={"Square_of_Exp":"Square_int"},inplace =True)
df1

,Department,Employee,Salary,Experience,City,Dept_avg_salary,salary_percent,Salary_dif,Square_int
0,HR,A,40000,2,Bangalore,42500.000000,0.470588,-2500.000000,4
1,IT,B,60000,5,Chennai,62333.333333,0.320856,-2333.333333,25
2,IT,C,65000,6,Kochi,62333.333333,0.347594,2666.666667,36
3,HR,D,45000,2,Kochi,42500.000000,0.529412,2500.000000,4
4,Finance,E,70000,8,Chennai,71000.000000,0.492958,-1000.000000,64
5,IT,F,62000,4,Kochi,62333.333333,0.331551,-333.333333,16
6,Finance,G,72000,8,Mumbai,71000.000000,0.507042,1000.000000,64

In [64]:
import pandas as pd

df1 = pd.DataFrame({
"EmpID": [1, 2, 3, 4],
"Name": ["A", "B", "C", "D"],
"DeptID": [101, 102, 103, 104]
})

df2 = pd.DataFrame({
"DeptID": [101, 102, 105],
"Department": ["HR", "IT", "Finance"]
})
print(df1)
print()
print(df2)

   EmpID Name  DeptID
0      1    A     101
1      2    B     102
2      3    C     103
3      4    D     104

   DeptID Department
0     101         HR
1     102         IT
2     105    Finance

In [58]:
pd.merge(df1,df2,on='DeptID',how='inner')

   EmpID Name  DeptID Department
0      1    A     101         HR
1      2    B     102         IT

In [59]:
pd.merge(df1,df2,on='DeptID',how='outer')

   EmpID Name  DeptID Department
0    1.0    A     101         HR
1    2.0    B     102         IT
2    3.0    C     103        NaN
3    4.0    D     104        NaN
4    NaN  NaN     105    Finance

In [60]:
pd.merge(df1,df2,on='DeptID',how='left')

   EmpID Name  DeptID Department
0      1    A     101         HR
1      2    B     102         IT
2      3    C     103        NaN
3      4    D     104        NaN

In [61]:
pd.merge(df1,df2,on='DeptID',how='right')

   EmpID Name  DeptID Department
0    1.0    A     101         HR
1    2.0    B     102         IT
2    NaN  NaN     105    Finance

In [66]:
import pandas as pd

students = pd.DataFrame({
"student_id": [101, 102, 103, 104, 105, 106],
"student_name": ["Anu", "Rahul", "Meera", "Arun", "Diya", "Vivek"],
"course_id": ["C01", "C02", "C03", "C04", "C05", "C06"],
"marks": [85, 78, 92, 67, 88, 73]
})

courses = pd.DataFrame({
"course_id": ["C01", "C02", "C03", "C04", "C07", "C08"],
"course_name": [
"Python",
"Data Science",
"Machine Learning",
"Power BI",
"Generative AI",
"Cloud Computing"
],
"trainer": ["Anjali", "Rahul", "Meera", "Arun", "Neha", "Vishnu"]
})

In [68]:
print(students)
print("*"*50)
print(courses)

   student_id student_name course_id  marks
0         101          Anu       C01     85
1         102        Rahul       C02     78
2         103        Meera       C03     92
3         104         Arun       C04     67
4         105         Diya       C05     88
5         106        Vivek       C06     73
**************************************************
  course_id       course_name trainer
0       C01            Python  Anjali
1       C02      Data Science   Rahul
2       C03  Machine Learning   Meera
3       C04          Power BI    Arun
4       C07     Generative AI    Neha
5       C08   Cloud Computing  Vishnu

In [80]:
# Q1

#Create a report that shows only students who have a valid course assigned to them.
#Display the student name, course name, trainer, and marks.

In [79]:
result = pd.merge(students,courses,on='course_id',how='inner')
print(result[['student_name','course_name','trainer','marks']])

  student_name       course_name trainer  marks
0          Anu            Python  Anjali     85
1        Rahul      Data Science   Rahul     78
2        Meera  Machine Learning   Meera     92
3         Arun          Power BI    Arun     67

In [ ]:
# Q2

# Create a report that contains every student, whether or not their course information is available.
#Display the student name, course name, and marks.

In [ ]:
# Q3

# Create a report that contains every course, including courses where no student has registered.
# Display the course name, trainer, and student name.

In [ ]:
# Q4

# Create a report that contains all students and all courses, including records that do not have a matching course_id.
# Display the student name, course name, trainer, and marks.

In [83]:
result4 = pd.merge(students,courses,on='course_id',how='right')
print(result4[['student_name','course_name','trainer','marks']])

  student_name       course_name trainer  marks
0          Anu            Python  Anjali   85.0
1        Rahul      Data Science   Rahul   78.0
2        Meera  Machine Learning   Meera   92.0
3         Arun          Power BI    Arun   67.0
4          NaN     Generative AI    Neha    NaN
5          NaN   Cloud Computing  Vishnu    NaN