join

In [9]:
import pandas as pd

# Create sample DataFrames
df1 = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Anu", "Bala", "Chetan"],
    "Salary": [50000, 60000, 70000]
})

df3 = pd.DataFrame({
    "Emp_id": [2, 3, 4],
    "Name": ["Bala", "Chetan", "Divya"],
    "Salary": [65000, 75000, 80000]
})

In [12]:
print(df1.columns)
print()
print(df3.columns)

Index(['EmpID', 'Name', 'Salary'], dtype='str')

Index(['Emp_id', 'Name', 'Salary'], dtype='str')

In [13]:
df1 = df1.set_index("EmpID")

In [14]:
df1.columns

Index(['Name', 'Salary'], dtype='str')

In [15]:
df1 = df1.join(df3)

ValueError: columns overlap but no suffix specified: Index(['Name', 'Salary'], dtype='str')

In [16]:
df = pd.merge(df1,df3,on='EmpID',how='outer',suffixes = (_october,_november))

NameError: name '_october' is not defined

In [18]:
import pandas as pd

# Create sample DataFrames
df1 = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Anu", "Bala", "Chetan"],
    "Salary": [50000, 60000, 70000]
})

df3 = pd.DataFrame({
    "EmpID": [2, 3, 4],
    "Name": ["Bala", "Chetan", "Divya"],
    "Salary": [65000, 75000, 80000]
})

# Merge with suffix
df = pd.merge(df1, df3, on="EmpID", how="outer", suffixes=("_october", "_november"))
print(df1)

   EmpID    Name  Salary
0      1     Anu   50000
1      2    Bala   60000
2      3  Chetan   70000

In [19]:
df4 = pd.DataFrame({
    "EmpID": [11, 12, 13, 14],
    "Name": ["G", "H", "K", "X"],
    "DeptID": [108, 109, 107, 108]
})
df4

   EmpID Name  DeptID
0     11    G     108
1     12    H     109
2     13    K     107
3     14    X     108

In [23]:
pd.concat([df1,df4]) #by default axix =0

   EmpID    Name   Salary  DeptID
0      1     Anu  50000.0     NaN
1      2    Bala  60000.0     NaN
2      3  Chetan  70000.0     NaN
0     11       G      NaN   108.0
1     12       H      NaN   109.0
2     13       K      NaN   107.0
3     14       X      NaN   108.0

In [27]:
pd.concat([df1,df4],axis = 1)

   EmpID    Name   Salary  EmpID Name  DeptID
0    1.0     Anu  50000.0     11    G     108
1    2.0    Bala  60000.0     12    H     109
2    3.0  Chetan  70000.0     13    K     107
3    NaN     NaN      NaN     14    X     108

In [28]:
pd.concat([df1, df4], keys=["First", "Second"])

          EmpID    Name   Salary  DeptID
First  0      1     Anu  50000.0     NaN
       1      2    Bala  60000.0     NaN
       2      3  Chetan  70000.0     NaN
Second 0     11       G      NaN   108.0
       1     12       H      NaN   109.0
       2     13       K      NaN   107.0
       3     14       X      NaN   108.0