In [1]:
import pandas as pd

df = pd.read_csv("nba.csv")#csv file
#read_excel
#read_json
#read_sql
#read_table 

print(df)

              Name            Team  Number Position   Age Height  Weight  \
0    Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1      Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2     John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3      R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4    Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0
..             ...             ...     ...      ...   ...    ...     ...
453   Shelvin Mack       Utah Jazz     8.0       PG  26.0    6-3   203.0
454      Raul Neto       Utah Jazz    25.0       PG  24.0    6-1   179.0
455   Tibor Pleiss       Utah Jazz    21.0        C  26.0    7-3   256.0
456    Jeff Withey       Utah Jazz    24.0        C  26.0    7-0   231.0
457            NaN             NaN     NaN      NaN   NaN    NaN     NaN

               College     Salary
0                Texas  7730337.0
1            Marquette  6796117.0
2    Boston University        NaN
3        Georgia State  1148640.0
4                  NaN  5000000.0
..                 ...        ...
453             Butler  2433333.0
454                NaN   900000.0
455                NaN  2900000.0
456             Kansas   947276.0
457                NaN        NaN

[458 rows x 9 columns]

In [2]:
df.index

RangeIndex(start=0, stop=458, step=1)

In [3]:
df.sort_index()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df['Team'].unique()

<ArrowStringArray>
[        'Boston Celtics',          'Brooklyn Nets',        'New York Knicks',
     'Philadelphia 76ers',        'Toronto Raptors',  'Golden State Warriors',
   'Los Angeles Clippers',     'Los Angeles Lakers',           'Phoenix Suns',
       'Sacramento Kings',          'Chicago Bulls',    'Cleveland Cavaliers',
        'Detroit Pistons',         'Indiana Pacers',        'Milwaukee Bucks',
       'Dallas Mavericks',        'Houston Rockets',      'Memphis Grizzlies',
   'New Orleans Pelicans',      'San Antonio Spurs',          'Atlanta Hawks',
      'Charlotte Hornets',             'Miami Heat',          'Orlando Magic',
     'Washington Wizards',         'Denver Nuggets', 'Minnesota Timberwolves',
  'Oklahoma City Thunder', 'Portland Trail Blazers',              'Utah Jazz',
                      nan]
Length: 31, dtype: str

In [5]:
df['Team'].nunique()

30

In [6]:
df['Team'].value_counts()

Team
New Orleans Pelicans      19
Memphis Grizzlies         18
New York Knicks           16
Milwaukee Bucks           16
Boston Celtics            15
Brooklyn Nets             15
Philadelphia 76ers        15
Toronto Raptors           15
Golden State Warriors     15
Los Angeles Clippers      15
Los Angeles Lakers        15
Phoenix Suns              15
Sacramento Kings          15
Chicago Bulls             15
Cleveland Cavaliers       15
Detroit Pistons           15
Indiana Pacers            15
Dallas Mavericks          15
Houston Rockets           15
San Antonio Spurs         15
Atlanta Hawks             15
Charlotte Hornets         15
Miami Heat                15
Washington Wizards        15
Denver Nuggets            15
Oklahoma City Thunder     15
Portland Trail Blazers    15
Utah Jazz                 15
Orlando Magic             14
Minnesota Timberwolves    14
Name: count, dtype: int64

In [10]:
#loc and iloc

In [11]:
#1. Import Pandas
import pandas as pd
#2. Create Sample Dataset
data = {
"Name": ["Alice", "Bob", "Charlie", "David", "Emma"],
"Age": [23, 25, 22, 24, 26],
"Department": ["HR", "IT", "Finance", "IT", "Marketing"],
"Salary": [40000, 50000, 45000, 52000, 48000]
}

df = pd.DataFrame(data,index=[1,2,3,4,5])

print(df)

      Name  Age Department  Salary
1    Alice   23         HR   40000
2      Bob   25         IT   50000
3  Charlie   22    Finance   45000
4    David   24         IT   52000
5     Emma   26  Marketing   48000

In [ ]:
#if there is multiple results, ti will not print in the cell,so we have to use the print function to do that

In [12]:
print(df.loc[[2]])
print('*'*50)
print(df.iloc[[2]])

  Name  Age Department  Salary
2  Bob   25         IT   50000
**************************************************
      Name  Age Department  Salary
3  Charlie   22    Finance   45000

In [16]:
df_new = pd.DataFrame(data,index=['A','B','C','D','E'])
df_new

      Name  Age Department  Salary
A    Alice   23         HR   40000
B      Bob   25         IT   50000
C  Charlie   22    Finance   45000
D    David   24         IT   52000
E     Emma   26  Marketing   48000

In [31]:
print(df_new.iloc[1,3])

50000

In [44]:
df_new.iloc[1:3,-1]

B    50000
C    45000
Name: Salary, dtype: int64

In [46]:
df_new.loc[['A','D'],['Age','Department']]

   Age Department
A   23         HR
D   24         IT